<h2> Learning Outcome Report </h2>
<?php
$form = $this->element;

// get min length of report.
$minLen = $form->report->getValidator('StringLength')->getMin();

?>

<form action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>">
   <?php echo $form->report ?>
   <br />

   <p> Report must have a minimum of <span id="minLen" data-minlenfoo="Hello"><?php echo $minLen ?></span> characters </p>
   <p> Characters remaining: <span class="charsLeft"> <?php echo $minLen ?> </span>  </p>
   <p id="foobar" data-foo="Foo"> Foo </p>

   <?php echo $form->saveOnly ?>
   <?php echo $form->finalSubmit ?>
   <?php echo $form->submittedassignments_id ?>
   <?php echo $form->lastPage ?>




</form>