<?php
$form = $this->element;

// get min length of report.
$minLen = $form->report->getValidator('StringLength')->getMin();

?>

<form action="<?php echo $form->getAction() ?>" method="<?php echo $form->getMethod() ?>">
   <?php echo $form->report ?>
   <br />

   <p> Report must have a minimum of <span id="minLen"> <?php echo $minLen ?> </span> characters </p>
   <p> Characters remaining: <span id="charsLeft"> <?php echo $minLen ?> </span>  </p>

   <?php echo $form->saveOnly ?>
   <?php echo $form->finalSubmit ?>




</form>