<?php
$form = $this->element;
?>

<form class="midtermReport" id='midtermReportForm' method="<?php echo $form->getMethod(); ?>" >

   <!-- Loop through form -->
   <?php foreach ($form as $f) { ?>
      
      <?php 
      if ($f instanceof Zend_Form_Element_Textarea) {
         echo $f->getLabel() . "<br />";

         echo $f . "<br />"; 

         $minLen = $f->getValidator('StringLength')->getMin();

         // The <span> in this string holds the minimum length so it can be retrieved in
         // the JavaScript.
         $elemId = $f->getId();
         echo "Answer much be at least <span id='minLen-$elemId'> $minLen </span> characters long. <br />";
         echo "Remaining characters: <span id='charsLeft-$elemId'> $minLen </span> <br /><br /><br /><br />";
      }
      ?>

   <?php } ?>
   <!-- End Loop -->

   <?php echo $form->saveOnly ?>
   <?php echo $form->finalSubmit ?>

</form>