<?php
$coopSess = new Zend_Session_Namespace('coop');
echo $this->headLink()->appendStylesheet($coopSess->baseUrl.'/css/views/assignments/supervisor-eval.css'); 
$elems = $this->element;
?>

<form id="studentEvalForm" method="POST" action="<?php echo $elems->getAction ?>">

    <?php 
        echo $this->partial('assignment/partials/jobsite-fields.phtml', 
                array('static_tasks' => $elems->static_tasks));
    ?>
    
   <div class="clear"></div>

   <br /> <br /> <br />

   <div style="text-align:center;">
      <h3> TOTAL NUMBER OF HOURS WORKED </h3>
   </div>

   
   
   
   <table>
      <tr>
         <th> Fall Semester </th>
         <th> Hours </th>
         <th> Spring Semester </th>
         <th> Hours </th>
         <th> Summer Semester </th>
         <th> Hours </th>
      </tr>

      <tr>
         <td> August ___ thru 31 </td>
         <td> <?php echo $elems->static_tasks->fallHrs1 ?> </td>

         <td> January ___ thru 31 </td>
         <td> <?php echo $elems->static_tasks->springHrs1 ?> </td>
         
         <td> May ___ to June 30 </td>
         <td> <?php echo $elems->static_tasks->summerHrs1 ?> </td>
      </tr>


      <tr>
         <td> September 1 thru 30 </td>
         <td> <?php echo $elems->static_tasks->fallHrs2 ?> </td>

         <td> February 1 thru 28 </td>
         <td> <?php echo $elems->static_tasks->springHrs2 ?> </td>
         
         <td> July 1 to August __ </td>
         <td> <?php echo $elems->static_tasks->summerHrs2 ?> </td>
      </tr>

      <tr>
         <td> October 1 thru 31 </td>
         <td> <?php echo $elems->static_tasks->fallHrs3 ?> </td>

         <td> March 1 thru 31 </td>
         <td> <?php echo $elems->static_tasks->springHrs3 ?> </td>

         <td></td>
         <td></td>
      </tr>
      
      <tr>
         <td> November 1 thru 30 </td>
         <td> <?php echo $elems->static_tasks->fallHrs4 ?> </td>

         <td> April 1 thru 30 </td>
         <td> <?php echo $elems->static_tasks->springHrs4 ?> </td>
         
         <td></td>
         <td></td>
      </tr>
      
      <tr>
         <td> December 1 thru __ </td>
         <td> <?php echo $elems->static_tasks->fallHrs5 ?> </td>

         <td> May 1 thru __ </td>
         <td> <?php echo $elems->static_tasks->springHrs5 ?> </td>
         
         <td></td>
         <td></td>
      </tr>
      
      <tr>
         <td> <b>Total Hours</b> </td>
         <td> <?php echo $elems->static_tasks->fallTotalHrs ?> </td>

         <td> <b>Total Hours</b> </td>
         <td> <?php echo $elems->static_tasks->springTotalHrs ?> </td>
         
         <td> <b>Total Hours</b> </td>
         <td> <?php echo $elems->static_tasks->summerTotalHrs ?> </td>
      </tr>
      
   </table>

   <br /> <br />

   <?php echo $elems->saveOnly ?> 
   <?php 
       if ($coopSess->role === 'coordinator') {
           echo $elems->finalSubmit;
       } 
   ?>

   <?php echo $elems->pdfSubmit ?>


</form>
