<?php
   $search =  $this->searchForm;
   $students = $this->students;

   $incompletesUrl  = $this->url( array('controller' => 'incompletes', 'action' => 'index') );
?>

<h3> Search </h3>
<form method="POST">
   <input type="hidden" name="submittedForm" value="searchForm" />
   <?php echo $search->classes_id ?>
   <?php echo $search->semesters_id ?>
   <input type="submit" value="Search" />
</form> <br /><br />


<?php if (isset($students)) { ?>

   <a class="regText" href="<?php echo $incompletesUrl ?>"> View incomplete students </a> <br /> <br />

   <h2> Students With NO Incomplete Status </h2>
   <h4> Select students, then click submit button below to mark them as 'Incomplete' </h4>

   <?php echo $this->partial('incompletes/_students_table.phtml', 
                 array('students'      => $students, 
                       'submitLabel'   => "Mark as incomplete", 
                       'searchClassId' => $this->searchClassId, 
                       'searchSemId'   => $this->searchSemId)) ?>

<?php } ?>