<?php
   $result = $this->result;
?>

<style>
   table#incompletes th,td {
      text-align: center;
      border: 1px solid;
      padding: 10px 3px 10px 3px;
   }
</style>

<h2> Incomplete Students </h2>

<form method="POST">
   <table id="incompletes">
      <tr>
         <th> <input id="check-all" type="checkbox" /> </th>
         <th> Name </th>
         <th> Class </th>
         <th> Semester </th>
      </tr>

      <?php foreach ($result as $res) { ?>
      <tr>
         <td> <input type="checkbox" class="incomplete-check-box" name="incompletes[]" value="<?php echo $res['users_sem_id'] ?>" /> </td>
         <td> <?php echo $res['lname'] . ", " . $res['fname'] . " (" . $res['username'] . ")" ?> </td>
         <td> <?php echo $res['class'] ?> </td>
         <td> <?php echo $res['semester'] ?> </td>
      </tr>

      <?php } ?>

   </table>

   <input type="submit" value="Remove Incomplete Status" />
</form>



<script type="text/javascript">
   $(document).ready(function() {
      $("#incompletes").on('click', '#check-all', function() {
         if( $(this).is(':checked') ) {
            $(".incomplete-check-box").prop('checked', true)
         } else {
            $(".incomplete-check-box").prop('checked', false)
         }
      })
   })

</script>