<style>
   .loginButton {
      position: fixed;
      left: 50%;
   }
</style>
<?php
   //echo $this->message . "<br /><br />";
   //echo $this->form;
   $loginUrl = $this->url(array('action' => 'cas', 'controller' => 'auth'));
?>

<b> <?php echo $this->message; ?> </b> <br /><br />
<?php echo $this->form; ?>

<!-- <button class="loginButton span-3 last push-12" onclick="location.href='<?php echo $loginUrl ?>'"> <h2>Log In</h2> </button> -->

<script>
   $(document).ready(function() {
      $("#username").focus()
   })
</script>