<?php

   $coopSess = new Zend_Session_Namespace('coop');

   // include tiny_mce.js for just this page
   $this->headScript()->appendFile($coopSess->baseUrl.'/js/tinymce/jscripts/tiny_mce/tiny_mce.js');
   echo $this->headScript();

   $classId = $this->classId; // hidden
   $sylText = $this->sylText; // textarea value
   //die(var_dump($classId));

   $formAction = $coopSess->baseUrl . "/syllabus/edit";

?>

<?php if ($classId === false) { // if no class was chosen first ?>

   <p class="error"> Must select a class first </p>

<?php } else { ?>

   <?php echo $this->message // success or error message ?>

   <form action="<?php echo $formAction ?>" method="POST" id="editSyllabus" >

      <textarea name="syllabus" class="editSyllabus"> <?php echo $sylText ?> </textarea> <br /><br />

      <input type="checkbox" name="isFinal" value="1" />

      <span style="font-size:16px;"> Submit as final? </span> <br /> <br /> 

      <input type="hidden" name="classId" value="<?php echo $classId ?>" />

      <input type="submit" value="Submit" />

   </form>

<?php } ?>

<script type="text/javascript">
   $('document').ready(function() {
        //$("#syllabus_spellchecker").trigger('click');
   });


   tinyMCE.init({
        mode : "textareas",
        plugins : "spellchecker,searchreplace,paste,table",

        // this file is a copy of the default content.css file in tinymce. font-size of 
        // the line containing "body, td, pre" was changed to give a different default font size.
        content_css : base + "/css/tinymce_custom_content.css",

        theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "pastetext,pasteword,|,bullist,numlist,|,outdent,indent,undo,redo,forecolor,backcolor,spellchecker,tablecontrols",
        theme_advanced_resizing : true
   });

</script>
