<?php
   $courses = $this->courses;
   echo "<table>";
   foreach ($courses as $c) { 
      $id = $c['id'];
      $name = $c['name'];
      $viewUrl = $this->url(array('action' => 'view'));
      $editUrl = $this->url(array('action' => 'edit'));
      
//      echo "<tr>";
//      echo    "<a href='$url?id=$id'>$name</a>";
//      echo "</tr><br />";
      
      echo "<tr>";
      echo    "<td>$name</td>";
      echo    "<td> <a href='$viewUrl?id=$id'>View</a> </td>";
      echo    "<td> <a href='$editUrl?id=$id'>Edit</a> </td>";
      echo "</tr>";
      
   }
   echo "</table>";
?>
<table>