<?php
   if ($this->class) {
      $coopSess = new Zend_Session_Namespace('coop');
      $role = $coopSess->role;
      $class = $this->class;
      $id = $class['id'];
      $name = $class['name'];
      $syllabus = $class['syllabus'];
      
      echo "<h1>$name</h1>";
      echo "<div>";
      echo    "$syllabus";
      echo "</div>";

      if ($role == 'coordinator') {
         $editUrl = $this->url(array('action'=>'edit'));
         echo "<a href='$editUrl?id=$id'>Edit</a>";
      }
   }
   
?>
