<?php
$elems = $this->element;
?>

<form method="POST" id="studentEvalForm" action="" >

   <?php echo $elems->dynamic_tasks ?>

   
   
   
   
   
   
   
   
   
   
   <h4> <b> The Student Agrees To: </b> </h4>

   <ol>
      <li> Maintain regular attendance a school and work, and notify the school and employer prior to any absence; </li>

      <li> Complete assignments on time, show honesty, punctuality, a cooperative attitude, proper grooming/dress, and willingness to learn; </li>

      <li> Consult the Co-op coordinator and work supervisor about any problems; and,</li>
      
      <li> Conform to the rules and regulations of the worksite, and maintain confidentiality. </li>

   </ol>

   <h4> <b> The Employer Agrees To: </b></h4>

   <ol>
      <li> Provide thorough orientation to job and worksite, as well as a meaningful, well-supervised work experience;</li>

      <li> Provide evaluation of performance, time for consultation with, and on-site monitoring visits by Co-op coordinator; </li>

      <li> Consult Co-op coordinator regarding problems related to the work experience, and prior to suspension or termination; </li>

      <li> Conform to all State and Federal laws which prohibit discrimination and promote affirmative action and adhere to the UH EEO/AA Policy </li>

      <li> Offer jobs that pay a base salary equal to or greater than a minimum wage in compliance with city/state/federal labor laws and ordinances 
           or provide internship training as compensation. </li>

      <li> Provide adequate protection to the student through Workman's Compensation and/or liability insurance (required by law) </li>

   </ol>


   <?php echo $this->element->Submit ?>

</form>