<?php
$elems = $this->element;
?>

<form method="POST" class="coopAgreementForm"  submissionid="<?php echo $elems->getAttrib('submissionid') ?>" >
   
   <?php echo $elems->static_tasks->id ?>
   
   <?php echo $elems->static_tasks->position ?>
   <?php echo $elems->static_tasks->company ?>
   <?php echo $elems->static_tasks->hrs_per_week ?> <br />

   <?php echo $elems->static_tasks->semester_dates ?>
   <?php echo $elems->static_tasks->supervisor ?>
   <?php echo $elems->static_tasks->phone ?> <br /><br /><br /><br />
   
   
   <h4> <b> The Student Agrees To: </b> </h4>

   <ol>
      <li> Maintain regular attendance a school and work, and notify the school and employer prior to any absence; </li>

      <li> Complete assignments on time, show honesty, punctuality, a cooperative attitude, proper grooming/dress, and willingness to learn; </li>

      <li> Consult the Co-op coordinator and work supervisor about any problems; and,</li>
      
      <li> Conform to the rules and regulations of the worksite, and maintain confidentiality. </li>

   </ol>

   <h4> <b> The Employer Agrees To: </b></h4>

   <ol>
      <li> Provide thorough orientation to job and worksite, as well as a meaningful, well-supervised work experience;</li>

      <li> Provide evaluation of performance, time for consultation with, and on-site monitoring visits by Co-op coordinator; </li>

      <li> Consult Co-op coordinator regarding problems related to the work experience, and prior to suspension or termination; </li>

      <li> Conform to all State and Federal laws which prohibit discrimination and promote affirmative action and adhere to the UH EEO/AA Policy </li>

      <li> Offer jobs that pay a base salary equal to or greater than a minimum wage in compliance with city/state/federal labor laws and ordinances 
           or provide internship training as compensation. </li>

      <li> Provide adequate protection to the student through Workman's Compensation and/or liability insurance (required by law) </li>

   </ol> <br />

   
   <div style="border-bottom: 1px solid;border-top: 1px solid;text-align: center;"> 
      <h4> 
         <b>PLEASE INDICATE HOW IMPORTANT THE TASKS BELOW ARE FOR STUDENT SUCCESS AT WORK </b> <br /> 
      </h4> 
   </div> <br />
   

   <?php 
      foreach ($elems->dynamic_tasks as $t) {
         echo $t . "<br /><br />";
      }
   ?>

   
   
                     <!-- IF CLASS IS BELOW 193 --> 
                     
   <?php if (isset($elems->static_tasks->duties)) { ?>
      <div style="border-bottom: 1px solid;border-top: 1px solid;text-align: center;"> 
         <h4> 
            <b>Please describe briefly the duties and performance objective as assigned to 
               this student during the co-op period. </b> <br /> 
         </h4> 
      </div> <br />

      <?php echo $elems->static_tasks->duties ?>

      
                       <!-- ELSE IF CLASS IS 193 OR ABOVE --> 
   <?php } else {?>

      <div style="border-bottom: 1px solid;border-top: 1px solid;text-align: center;"> 
         <h4> 
            <b> 
                The Student will achieve the following Learning Objective(s) during this work 
                period <br />
                (Complete one objective for each credit that the student is enrolled in 
                for the semester)
            </b> <br /> 
         </h4> 
      </div> <br />

      <?php echo $elems->static_tasks->lrnObjective1 ?> <br />
      <?php echo $elems->static_tasks->lrnObjective2 ?> <br />


   <?php } ?>

   <br /> <br />

   <?php echo $elems->saveOnly ?> 
   <?php echo $elems->finalSubmit ?> 

   
   
   
   
   
   
   
   
   
   


   <?php echo $this->element->Submit ?>

</form>