<?php
$coopSess = new Zend_Session_Namespace('coop');
echo $this->headLink()->appendStylesheet($coopSess->baseUrl.'/css/views/assignments/supervisor-eval.css'); 
$elems = $this->element;
?>

<form method="POST" class="coopAgreementForm"  submissionid="<?php echo $elems->getAttrib('submissionid') ?>" >
    
    
   <?php echo $elems->static_tasks->id ?>
    
    
   <?php 
       echo $this->partial('assignment/partials/jobsite-fields.phtml', 
               array('static_tasks' => $elems->static_tasks));
   ?>


   <div class="clear"></div>
   
   <br /><br /><br />
   

   <?php echo $this->render("form/partials/_coop-agreement-agrees-to-list.phtml") ?>
   
   
   <div style="border-bottom: 1px solid;border-top: 1px solid;text-align: center;"> 
      <h4> 
         <b>PLEASE INDICATE HOW IMPORTANT THE TASKS BELOW ARE FOR STUDENT SUCCESS AT WORK </b> <br /> 
      </h4> 
   </div> <br />
   

   <?php 
      foreach ($elems->dynamic_tasks as $t) {
         echo $t . "<br /><br />";
      }
      echo $elems->static_tasks->other . "<br />&nbsp&nbsp&nbsp&nbsp&nbsp" . $elems->static_tasks->other_rating . "<br /> <br />";
   ?>

   
   
                     <!-- IF CLASS IS BELOW 193 --> 
                     
   <?php if (isset($elems->static_tasks->duties)) { ?>
      <div style="border-bottom: 1px solid;border-top: 1px solid;text-align: center;"> 
         <h4> 
            <b>Please describe briefly the duties and performance objective as assigned to 
               this student during the co-op period. </b> <br /> 
         </h4> 
      </div> <br />

      <?php echo $elems->static_tasks->duties ?>

      
                       <!-- ELSE IF CLASS IS 193 OR ABOVE --> 
   <?php } else {?>

      <div style="border-bottom: 1px solid;border-top: 1px solid;text-align: center;"> 
         <h4> 
            <b> 
                The Student will achieve the following Learning Objective(s) during this work 
                period <br />
                (Complete one objective for each credit that the student is enrolled in 
                for the semester)
            </b> <br /> 
         </h4> 
      </div> <br />

      <?php echo $elems->static_tasks->lrnObjective1 ?> <br />
      <?php echo $elems->static_tasks->lrnObjective2 ?> <br />

      <?php 
         if (isset($elems->static_tasks->lrnObjective3)) {
             echo $elems->static_tasks->lrnObjective3;
         }
      ?>



   <?php } ?>

   <br /> <br />

   <?php echo $elems->saveOnly ?> 
   <?php echo $elems->finalSubmit ?> 


</form>