<?php
   $coopSess = new Zend_Session_Namespace('coop');

   // include tiny_mce.js for just this page
   $this->headScript()->appendFile($coopSess->baseUrl.'/js/tinymce/jscripts/tiny_mce/tiny_mce.js');
   echo $this->headScript();

   echo $this->message;

   echo $this->form;
?>

<script type="text/javascript">
   $('document').ready(function() {
        //$("#syllabus_spellchecker").trigger('click');
   });


   tinyMCE.init({
        mode : "textareas",
        plugins : "spellchecker,searchreplace,paste,table",

        // this file is a copy of the default content.css file in tinymce. font-size of 
        // the line containing "body, td, pre" was changed to give a different default font size.
        content_css : base + "/css/tinymce_custom_content.css",

        theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "pastetext,pasteword,|,bullist,numlist,|,outdent,indent,undo,redo,forecolor,backcolor,spellchecker,tablecontrols",
        theme_advanced_resizing : true
   });

</script>