<?php
   $coopSess = new Zend_Session_Namespace('coop');
   $this->headLink()->appendStylesheet($coopSess->baseUrl.'/css/jquery_datepicker/ui.all.css');

   $this->pageTitle = "Student Information Sheet";
   echo $this->message;
   echo $this->form;
?>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.5.3/jquery-ui.min.js"></script> 
<script type="text/javascript"> 
   $('document').ready(function(){
         //$("#grad_date").datepicker({ showOn: 'button', buttonText: "Calendar", buttonImageOnly: true, buttonImage: base + "/images/x_office_calendar.png", constrainInput: false });
         $("#empInfo-start_date").datepicker({ showOn: 'button', buttonText: "Calendar", 
               buttonImageOnly: true, buttonImage: base + "/images/x_office_calendar.png", constrainInput: false });
         $("#empInfo-end_date").datepicker({ showOn: 'button', buttonText: "Calendar", 
               buttonImageOnly: true, buttonImage: base + "/images/x_office_calendar.png", constrainInput: false });
   });
 </script> 
