<?php
   $coopSess = new Zend_Session_Namespace('coop');
   $this->headLink()->appendStylesheet($coopSess->baseUrl.'/css/jquery_datepicker/ui.all.css');

   $this->pageTitle = "Student Information Sheet";
   if ($this->isDue) {
       echo "<p class=error> This assignment is past it's due date </p>";
   } else {
       $url = $this->url( array('action' => 'student-info-edit'));
       echo "<h4> <a href='$url'> View Saved Student Information Sheets </a> </h4> <br />";
       echo $this->message;
       echo $this->form;
   }
?>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.5.3/jquery-ui.min.js"></script> 
<script type="text/javascript"> 
   $('document').ready(function(){
      $("#finalSubmit").live('click', function() {
         if (!confirm("Really submit?")) {
            return false;
         }
      });
         //$("#grad_date").datepicker({ showOn: 'button', buttonText: "Calendar", buttonImageOnly: true, buttonImage: base + "/images/x_office_calendar.png", constrainInput: false });
         //$("#empInfo-start_date").datepicker({ showOn: 'button', buttonText: "Calendar", 
         //      buttonImageOnly: true, buttonImage: base + "/images/x_office_calendar.png", constrainInput: false });
         //$("#empInfo-end_date").datepicker({ showOn: 'button', buttonText: "Calendar", 
         //      buttonImageOnly: true, buttonImage: base + "/images/x_office_calendar.png", constrainInput: false });
   });
 </script> 
