<?php
$this->pageTitle = "Your Saved Student Information Sheets";
if ($this->isDue) {
    echo "<p class=error> This assignment is past it's due date </p>";

} else {
    $url = $this->url( array('action' => 'student-info-show') );

    echo "<h3> <a href='$url'> Create New </a> </h3>";

    $form = $this->form;

    $page = 0;
    echo "<ul class='paging'>";
    foreach ($form->submissions as $s) {
       echo "<li class='simplePagerPage$page'>";
       echo "<br /> <br /> $s";
       echo "</li>";
    }
    echo "</ul>";
}
?>

<script type="text/javascript">
   $(document).ready(function() {
      $("ul.paging").quickPager( {pageSize : 1, pagerLocation : "both"} );
      $('.simplePagerNav').after('<br />');
      
      // Add confirmation to submit button
      $("#finalSubmit").live('click', function() {
         if (!confirm("Really submit?")) {
            return false;
         }
      });

      /* TEST FOR COORD VIEW */
      //$(".submit").live('click', function(e) {
      //   e.preventDefault();
      //   form = $(this).parent();
      //   //elems = $(form + " [name^='empInfo[']");

      //   elems = form.find("input[name^='empInfo[']");

      //   empInfo = {};
      //   // create function for this loop.
      //   elems.each(function() {
      //      name = $(this).attr('name');
      //      name = name.replace('empInfo[', '').replace(']', '');
      //      val = $(this).val();
      //      empInfo[name] = val;
      //   });

      //   $.post(base + '/form/student-info-edit', { 'empInfo': empInfo }, function(resp) {
      //      form.append(resp);

      //   });

      //});


   });
   

</script>