<?php
$this->pageTitle = "Your Saved Student Information Sheets";
$url = $this->url( array('action' => 'student-info-show') );

echo "<h3> <a href='$url'> Create New </a> </h3>";

$form = $this->form;

$page = 0;
echo "<ul class='paging'>";
foreach ($form->submissions as $s) {
   echo "<li class='simplePagerPage$page'>";
   echo "<br /> <br /> $s";
   echo "</li>";
}
echo "</ul>";
?>

<script type="text/javascript">
   $(document).ready(function() {

      $("ul.paging").quickPager( {pageSize : 1, pagerLocation : "both"} );
      $('.simplePagerNav').after('<br />');

   });
   

</script>