<?php
$elem = $this->element;


?>

<div style="border-bottom: 1px solid;border-top: 1px solid;text-align: center;"> 
   <h4> 
      <b> PERSONAL INFORMATION </b> <br /> 
   </h4> 
</div> <br />

<form id="studentInfoSheetForm" name="studentInfoSheet" method="<?php echo $this->element->getMethod(); ?>" action="<?php echo $this->element->getAction(); ?>" >
<table id=" "class="tableform">

   <tr>

      <td> 
         <?php echo $elem->personalInfo->fname ?> 
      </td>

      <td>
         <?php echo $elem->personalInfo->lname ?> 
      </td>

      <td>
         <?php echo $elem->personalInfo->uuid ?> 
      </td>

   </tr>
   
   <tr>

      <td>
         <?php echo $elem->personalInfo->mobile ?> 
      </td>
      
      <td>
         <?php echo $elem->personalInfo->email ?> 
      </td>
      
      <td>
         <?php echo $elem->personalInfo->phone ?> 
      </td>

   </tr>
   
   
   
</table>
   
<div style="border-bottom: 1px solid;border-top: 1px solid;text-align: center;"> 
   <h4> 
      <b> EDUCATION INFORMATION </b> <br /> 
   </h4> 
</div> <br />

<table class="tableform">
   <tr>
      <td>
         <?php echo $elem->eduInfo->majors_id ?>
      </td>

      <td>
         <?php echo $elem->eduInfo->semester_in_major ?>
      </td>
      
      <td>
         <?php echo $elem->eduInfo->grad_date ?>
      </td>

      <td>
         <?php echo $elem->eduInfo->classes_id ?>
      </td>
   </tr>

   <tr>
      <td>
         <?php echo $elem->eduInfo->coop_credits ?>
      </td>

      <td>
         <?php echo $elem->eduInfo->total_credits ?>
      </td>
      
      <td>
         <?php echo $elem->eduInfo->coop_sem_yr ?>
      </td>

      <td>
         <?php echo $elem->empInfo->coop_jobtitle ?>
      </td>
   </tr>

</table>

<?php echo $elem->eduInfo->other_courses ?> <br />


<div style="border-bottom: 1px solid;border-top: 1px solid;text-align: center;"> 
   <h4> 
      <b> EMPLOYMENT INFORMATION (Complete this section if you are currently working at a job related to your major) </b> <br /> 
   </h4> 
</div> <br />

<table class="tableform">
   <tr>
      <td>
         <?php echo $elem->empInfo->job_title ?>
      </td>

      <td>
         <?php echo $elem->empInfo->start_date ?>
      </td>
      
      <td>
         <?php echo $elem->empInfo->end_date ?>
      </td>

      <td>
         <?php echo $elem->empInfo->rate_of_pay ?>
      </td>
   </tr>

   <tr>
      <td>
         <?php echo $elem->empInfo->employer ?>
      </td>

      <td>
         <?php echo $elem->empInfo->department ?>
      </td>
      
      <td>
         <?php echo $elem->empInfo->street_address ?>
      </td>

      <td>
         <?php echo $elem->empInfo->city_state_zip ?>
      </td>
   </tr>

   <tr>
      <td>
         <?php echo $elem->empInfo->superv_name ?>
      </td>

      <td>
         <?php echo $elem->empInfo->superv_title ?>
      </td>
      
      <td>
         <?php echo $elem->empInfo->superv_phone ?>
      </td>

      <td>
         <?php echo $elem->empInfo->superv_email ?>
      </td>
   </tr>

   <tr>
      <td>
         <?php echo $elem->empInfo->fax ?>
      </td>
   </tr>
</table>


<div style="border-bottom: 1px solid;border-top: 1px solid;text-align: center;"> 
   <h4> 
      <b> ******** STUDENT PARTICIPATION AGREEMENT ******** </b> <br /> 
   </h4> 
</div> <br />

<p> Participation in Cooperative Education requires agreement with the terms and conditions below. By submitting this form, you agree to the following: </p> 

<ol>
   <li> I certify that to the best of my knowledge and belief, all of the information on and attached to this application is true, correct
        complete and made in good faith. I understand that this information may be investigated. </li>

   <li> I will maintain good academic standing at all times (at least 2.0 on a 4.0 scale in my major and cumulative G.P.A); </li>

   <li> I will maintain regular attendance at school and work, follow all rules, and notify my employer prior to any absence; </li>

   <li> I will demonstrate honesty, punctuality, a cooperative attitude, proper grooming/dress, and willingness to learn; </li>

   <li> I agree to consult the Co-op coordinator and work supervisor about any problems; </li>

   <li> I agree to conform to the rules and regulationsof the worksite, and maintain confidentiality; </li>

   <li> I wiill complete required assignments on time and finish necessary information, reports or time sheets; </li>

   <li> I hereby indemnify, defend and hold harmless the Employer and the University of Hawaii and the State of Hawaii, and their officers,
        employees, agents, or any person acting on their behalf from and against any claim or demand for loss, liability or damage connected 
        with the performance of this agreement, or made by reason of the non-performance of any of the terms, covenants and conditions herein, 
        or any Federal, state municipal or county rules; and, </li>

   <li> I authorize the Co-op coordinator to release information about my academic records to the Co-op Employer for puposes of obttaining or 
        maintaining employment. These records include grades, grade point aerage, courses attempted, courses completed, academic status 
        (probation, suspension, Dean's list, honor's graduate) and any other information contained in my academic history. 
        This authorization is valid for 5 years from the date signed.</li>

</ol>

<?php echo $elem->saveOnly ?>
<?php echo $elem->finalSubmit ?>


</form>
   





<!-- <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.5.3/jquery-ui.min.js"></script> 
<script type="text/javascript"> 
   $('document').ready(function(){
         $("#grad_date").datepicker({ showOn: 'button', buttonText: "Calendar", buttonImageOnly: true, buttonImage: base + "/images/x_office_calendar.png", constrainInput: false });
         $("#start_date").datepicker({ showOn: 'button', buttonText: "Calendar", buttonImageOnly: true, buttonImage: base + "/images/x_office_calendar.png", constrainInput: false });
         $("#end_date").datepicker({ showOn: 'button', buttonText: "Calendar", buttonImageOnly: true, buttonImage: base + "/images/x_office_calendar.png", constrainInput: false });
   });
 </script> -->