<div id="col1-fields">

    <?php echo $this->static_tasks->position ?> <br />
    <?php echo $this->static_tasks->semester_dates ?>
    <?php echo $this->static_tasks->coordinator ?>
    <?php echo $this->static_tasks->coord_email ?>

</div>


<div id="col2-fields">

    <?php echo $this->static_tasks->company ?> <br />
    <?php echo $this->static_tasks->supervisor ?>
    <?php echo $this->static_tasks->coord_phone ?>
    <?php echo $this->static_tasks->address ?>
</div>


<div id="col3-fields">

    <?php echo $this->static_tasks->hrs_per_week ?> <br />
    <?php echo $this->static_tasks->phone ?>
    <?php echo $this->static_tasks->college ?>
    <?php echo $this->static_tasks->fax ?>
</div>