<?php
   $classes = $this->classes;
   $url = $this->url(array('action' => 'edit', 'controller' => 'class'));
   $delUrl = $this->url(array('action' => 'delete', 'controller' => 'class'));
   $addUrl = $this->url(array('action' => 'create', 'controller' => 'class'));
   $count = 0;
   $page = 1;
?>

<h2> Manage Coop Classes </h2>

<p> <a href="<?php echo $addUrl ?>"> Add a class </a> </p>
<p> <a href="<?php echo $delUrl ?>"> Delete a class </a> </p>

<table class="classList">

<?php foreach ($classes as $c) { ?>

   <tr>
      <td class="className"> <?php echo $c['name'] ?> </td>

      <td class="editLink"> <a href='<?php echo "$url?id=".$c['id'] ?>' class="editLink"> EDIT </a> </td> 

   </tr>

   


<?php } ?>

</table>


<script type="text/javascript">

   $('document').ready(function() {
      

   });
   









</script>