<?php
   $deleteUrl = array("controller" => "user", "action" => "delete-extended-duedate");
?>

<table id='ext-duedates' class='stripe'>
    <tr>
        <th> Student </th> <th> Assignment </th> <th> Extended Due date </th>
    </tr>

    <?php foreach ($this->extDuedates as $e) { ?>
        <?php $deleteUrl['id'] = $e->id ?>
        <tr>
            <td> <?php echo $e->lname . ', ' . $e->fname . ' ('. $e->username . ')' ?> </td>
            <td> <?php echo $e->assignment ?> </td>
            <td> <?php echo $e->due_date ?> </td>
            <td> <a data-ext-duedate-id="<?php echo $e->id ?>" class="delete-extended-duedate" href="<?php echo $this->url($deleteUrl) ?>"> delete </a> </td>
        </tr>

    <?php } ?>

</table>


<script type="text/javascript"> 
   $(document).ready(function() {
      $(".delete-extended-duedate").live('click', function() {

         id = $(this).data('ext-duedate-id');
         
         filter = $("#extended-duedates-filter").data('filter');
         
         $.post(base + "/user/delete-extended-duedate", { 'id' : id, 'filter' : filter }, function(resp) {
            $("#async-container").html(resp);
         })


         return false;
      })
   })
</script>