<h2> Learning Outcome Report </h2>

<?php
   $coopSess = new Zend_Session_Namespace('coop');
   $this->headScript()->appendFile($coopSess->baseUrl.'/js/tinymce/jscripts/tiny_mce/tiny_mce.js');
   echo $this->headScript();

   $recText = $this->recText;

   if (!empty($recText)) {
      echo $recText['fname'] . " " . $recText['lname'] . "<br /> ";
      echo $recText['class'] . "<br /> ";
      echo $recText['semester'] . "<br /><br /><br />";
   }

   if ($this->submitted === false) {
      echo "<p class=error> Report has not been submitted </p>";
   } else {
      echo $this->report;
   }

?>