<h2> Learning Outcome Report </h2>

<?php
   $coopSess = new Zend_Session_Namespace('coop');
   $this->headScript()->appendFile($coopSess->baseUrl.'/js/tinymce/jscripts/tiny_mce/tiny_mce.js');
   echo $this->headScript();

   $recText = $this->recText;

   if (!empty($recText)) {
      echo $recText['fname'] . " " . $recText['lname'] . "<br /> ";
      echo $recText['class'] . "<br /> ";
      echo $recText['semester'] . "<br /><br /><br />";
   }

   if ($this->submitted === false) {
      echo "<p class=error> Report has not been submitted </p>";
   } else {
      echo "<ul class='paging'>";
      foreach ($this->form->submittedReports as $report) {
         echo "<li>";
         echo "<br /> <br />" . $report->report->getValue();
         echo "</li>";
      }
      echo "</ul>";
   }

?>

<script type="text/javascript">
   $(document).ready(function() {
      // Paging.
      $("ul.paging").quickPager( {pageSize : 1, pagerLocation : "both"} );
      $('.simplePagerNav').after('<br />');
   });
</script>