<h2> Midterm Report </h2>

<?php
   $coopSess = new Zend_Session_Namespace('coop');
   echo $this->headScript()->appendFile($coopSess->baseUrl . "/js/views/assignment/midterm-report.js");
   $recText = $this->recText;

   if (!empty($recText)) {
      echo $recText['fname'] . " " . $recText['lname'] . "<br /> ";
      echo $recText['class'] . "<br /> ";
      echo $recText['semester'] . "<br /><br /><br />";
   }

   if ($this->submitted === false) {
      echo "<p class=error> Report has not been submitted </p>";
   } else {
      echo $this->form;
   }

?>

<script type="text/javascript">

</script>