<h2> Resume </h2>
<?php
$form = $this->form;
$recText = $this->recText;

if (!empty($recText)) {
   echo $recText['fname'] . " " . $recText['lname'] . "<br /> ";
   echo $recText['class'] . "<br /> ";
   echo $recText['semester'] . "<br /><br /><br />";
}

if ($this->submitted === false) {
   echo "<p class=error> Report has not been submitted </p>";
} else {
   echo $form->static_tasks->resume->getValue();
}
?>
