<?php
   $coopSess = new Zend_Session_Namespace('coop');
   //echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/stripes-for-IE/IE9.js', 
   //                                     'text/javascript', 
   //                                     array('conditional' => 'lt IE 9'));
   
   $Assignment = new My_Model_Assignment();
   $due_date_column = $Assignment->getDuedateColumn();

   $recs = $this->recs;
   $recText = $this->recText;

   echo $recText['fname'] . " " . $recText['lname'] . "<br /> ";
   echo $recText['class'] . "<br /> ";
   echo $recText['semester'] . "<br /><br />";
?>


<table class="stripe">
   <th> Assignment </th> <th> Submitted? </th> <th> Date Submitted </th> <th> Due Date </th>

   <?php foreach ($recs as $r) { 
      if (!is_null($r['classes_id']) && $r['is_final']) {
         //$assignId = $r['assignments_id'];
         $assignNum = $r['assignment_num'];
         $submittedAssignId = $r['submittedassignments_id'];
         $subed = "<font color='green'> Yes </font> ";
         if ($assignNum !== '1') {
            $subed .= "<a href='#' class='undoSubmit' value='$submittedAssignId'> undo </a>";
         }
         $dateSubed = $r['date_submitted'];
      } else {
         $subed = "<font color='red'> No </font>";
         $dateSubed = "N/A";
      }
      
   ?>
      <tr> 
         <td> 
            <?php echo $r['assignment'] ?> 
         </td> 

         <td> 
            <?php echo $subed ?>
         </td> 

         <td>
            <?php echo $dateSubed ?>
         </td>

         <td>
            <?php echo $r[$due_date_column] ?>
         </td>
      </tr>


   <?php } // End foreach ?>
</table>


<script type="text/javascript"> 
   $(document).ready(function() {

      //stripeTable();

      $('a.undoSubmit').live('click', function(e) {
         e.preventDefault();
         //data = getRec();
         //alert(JSON.stringify(data, null, 4));
         id = $(this).attr('value');

         $.post(base + "/async/undo-submit", {'submittedassignments_id' : id}, function(resp) {
            $('#assignment-hist').click();
            //$('#asyncContainer').empty(resp);
            //$('#asyncContainer').append(resp);
         });

      });

   });

</script>