<?php
   $recs = $this->recs;
   $recText = $this->recText;

   echo $recText['fname'] . " " . $recText['lname'] . "<br /> ";
   echo $recText['class'] . "<br /> ";
   echo $recText['semester'] . "<br /><br />";
?>


<table>
   <th> Assignment </th> <th> Submitted? </th> <th> Date Submitted </th> <th> Due Date </th>

   <?php foreach ($recs as $r) { 
      if (!is_null($r['classes_id']) && $r['is_final']) {
         $subed = "<font color='green'> Yes </font>";
         $dateSubed = $r['date_submitted'];
      } else {
         $subed = "<font color='red'> No </font>";
         $dateSubed = "N/A";
      }
      
   ?>
      <tr> 
         <td> 
            <?php echo $r['assignment'] ?> 
         </td> 

         <td> 
            <?php echo $subed ?>
         </td> 

         <td>
            <?php echo $dateSubed ?>
         </td>

         <td>
            <?php echo $r['due_date'] ?>
         </td>
      </tr>


   <?php } // End foreach ?>
</table>