<!--[if lt IE 9]>
<?php 
   $coopSess = new Zend_Session_Namespace('coop');
   $this->headScript()->appendFile($coopSess->baseUrl.'/js/stripes-for-IE');
   echo $this->headScript();
?>
<![endif]--> 
<?php
   $coopSess = new Zend_Session_Namespace('coop');
   $this->headScript()->appendFile($coopSess->baseUrl.'/js/views/async/funcs.js');
   echo $this->headScript();

   $recs = $this->recs;
   $recText = $this->recText;

   echo $recText['fname'] . " " . $recText['lname'] . "<br /> ";
   echo $recText['class'] . "<br /> ";
   echo $recText['semester'] . "<br /><br />";
?>


<table>
   <th> Assignment </th> <th> Submitted? </th> <th> Date Submitted </th> <th> Due Date </th>

   <?php foreach ($recs as $r) { 
      if (!is_null($r['classes_id']) && $r['is_final']) {
         $assignId = $r['assignments_id'];
         $subed = "<font color='green'> Yes </font> <a href='#' class='undoSubmit' value='$assignId'> undo </a>";
         $dateSubed = $r['date_submitted'];
      } else {
         $subed = "<font color='red'> No </font>";
         $dateSubed = "N/A";
      }
      
   ?>
      <tr> 
         <td> 
            <?php echo $r['assignment'] ?> 
         </td> 

         <td> 
            <?php echo $subed ?>
         </td> 

         <td>
            <?php echo $dateSubed ?>
         </td>

         <td>
            <?php echo $r['due_date'] ?>
         </td>
      </tr>


   <?php } // End foreach ?>
</table>


<script type="text/javascript"> 
   $(document).ready(function() {

      $('a.undoSubmit').live('click', function(e) {
         e.preventDefault();
         data = getRec();
         //alert(JSON.stringify(data, null, 4));
         assignments_id = $(this).attr('value');

         $.post(base + "/async/undo-submit", {'data' : data, 'assignments_id' : assignments_id}, function(resp) {
            $('#assignment-hist').click();
            //$('#asyncContainer').empty(resp);
            //$('#asyncContainer').append(resp);
         });

      });

   });


   /* FUNCTIONS */

   // Gets the record information of the selected record (username, class, semester) to
   // use in queries for different assignment information.
   //function getRec() {
   //   // If the search results table (the table with student's name, class, semester, 
   //   // coordinator, etc.) is present, then the record information should be coming from
   //   // the selected record, so reset the stored record (#stored-rec) to that. 
   //   if ( $("#searchresults-table").length > 0 ) {
   //      $("#stored-rec").data("rec", "");
   //      rec = $("input[name=rec-choice]:checked").data('rec');
   //      $("#stored-rec").data("rec", rec);
   //   } 
   //   data = $("#stored-rec").data("rec");
   //   return data;
   //}

</script>