<h2> Student Information Sheet </h2>

<?php
   $coopSess = new Zend_Session_Namespace('coop');
   $this->headScript()->appendFile($coopSess->baseUrl.'/js/quickpager.jquery.js');
   echo $this->headScript();
   $recText = $this->recText;
   //die(var_dump($recText));
   $funcs = new My_Funcs();

   if (!empty($recText)) {
      echo $recText['fname'] . " " . $recText['lname'] . "<br /> ";
      echo $recText['class'] . "<br /> ";
      echo $recText['semester'] . "<br /><br /><br />";
   }

   // If $empinfo is empty, it means the student hasn't submitted it yet
   //if (empty($empinfo) || $this->submitted === false) {
   if ($this->submitted === false) {
      echo "<p class='error'> Form has not been submitted </p>";
   } else {

      $form = $this->form;
      $empForm = $form->getSubForm('empinfo[0]');
      $empinfo = $this->empinfo;

      // For each record of empinfo that the student has, echo a separate form and populate
      // the empinfo section of the form with the empinfo record.
      $page = 0;
      //echo "<div class='simplePagerContainer'>";
      echo "<ul class='paging'>";
      foreach ($empinfo as $e) {
         $page++;
         $e['start_date'] = $funcs->formatDateOut($e['start_date']);
         $e['end_date'] = $funcs->formatDateOut($e['end_date']);
         //$empForm->populate($e);
         $form->populate($e);
         $form->removeElement('Submit');
         echo "<li class='simplePagerPage$page'>";
         echo $form;
         echo "</li>";
      }
      echo "</ul>";
      //echo "</div>";
   }


?>


<script type="text/javascript">

   $('document').ready(function() {

      $("ul.paging").quickPager( {pageSize : 1, pagerLocation : "both"} );


      $('.simplePagerNav').after('<br />');

   });

</script>