<?php
   $url = $this->url(array('controller' => 'assignment', 'action' => 'properties'));
?>

<h2> Delete Questions </h2>

<p> <a class="regText" href="<?php echo "$url?id=$this->assignId" ?>"> Back to properties </a> </p>

<?php
   echo $this->message;
   echo $this->form;
?>

<script type="text/javascript">

   $('document').ready(function() {
      $('#deleteQuestion').bind("submit", function() {
         if (!confirm("Are you sure?")) {
            return false;
         }
      });

   });






</script>