<h2> Extend A Due Date </h2>


<?php
   echo $this->message;
   echo "<a class='regText' href='" . $this->url( array("controller" => "user", "action" => "view-extended-duedates") ) . "'> 
       View Extended Due Dates For This Semester </a>";
   echo "<br /> <br />";
   echo $this->form;
?>

<script type="text/javascript">

   $("document").ready(function() {
      // lastStudent is the last student selected when posting form.
      lastStudent = "<?php echo $this->lastStudent ?>"
      fillStudents(lastStudent);

      $("[name=classes_id]").change(function() {
         fillStudents();
      });


      /*
       * @param defaultValue If set, after pupulating the drop down, set the value
       *                     of the drop down to defaultValue.
       */
      function fillStudents(defaultValue) {
         val = $("[name=classes_id]").val();

         $.post(base + '/async/class-roll-json', {'classes_id' : val}, function(resp) {

            opts = resp;

            $("[name=username]").empty();

            optString = "";

            for (i = 0; i < opts.length; i++) {
               fname = opts[i].fname;
               lname = opts[i].lname;
               username = opts[i].username;

               optString += "<option value='" + username + "'>" +
                                lname + ", " + fname + " (" + username + ")" +
                            "</option>";
            }

            $("[name=username]").html(optString);

            if (typeof defaultValue !== "undefined") {
               $("#username").val(defaultValue)
            }

         }, 'json');
      }


   });

</script>
