<?php
$coopSess = new Zend_Session_Namespace('coop');
$this->headScript()->appendFile($coopSess->baseUrl.'/js/tinymce/jscripts/tiny_mce/tiny_mce.js');
echo $this->headScript();

$form = $this->form;
$errors = $this->errors;

if (!empty($errors)) {
   foreach ($errors as $e) {
      echo "<p class=error> $e </p>";
   }

}

$page = 0;
echo "<ul class='paging'>";
foreach ($form->savedReports as $saved) {
   echo "<li>";
   echo "<br /> <br /> $saved";
   echo "</li>";
}
echo "</ul>";
?>


<script type="text/javascript">
$(document).ready(function() {

   // Keep track of the last simplePager page before the form was submitted
   // so the page can be displayed when the view is reloaded.
   $("form").live("submit", function() {
      lastPage = $("li.currentPage").attr("class").replace("currentPage", "").trim();
      $(this).find("[name=lastPage]").val(lastPage);
   });


   $("ul.paging").quickPager( {pageSize : 1, pagerLocation : "both"} );
   $('.simplePagerNav').after('<br />');
   
   // Add confirmation to submit button
   $("#finalSubmit").live('click', function() {
      if (!confirm("Really submit?")) {
         return false;
      }
   });

   window.setInterval(function() {
      countChars();
   }, 500);

   initTinyMCE();

   
   // Set the simplePager page back to the last one viewed, if any.
   lastPage = "<?php echo $this->lastPage ?>"
   if (lastPage) {
      $("li." + lastPage + " a").click();
   }
   

});


   /* FUNCTIONS */

function initTinyMCE()
{
   tinyMCE.init({
      mode : "textareas",
      plugins : "spellchecker,searchreplace,paste,table",
      theme_advanced_resizing_min_height : 800,
      theme_advanced_resizing_max_width : 1020,

      // this file is a copy of the default content.css file in tinymce. font-size of 
      // the line containing "body, td, pre" was changed to give a different default font size.
      content_css : base + "/css/tinymce_custom_content.css",

      theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,fontselect,fontsizeselect",
      theme_advanced_buttons2 : "pastetext,pasteword,|,bullist,numlist,|,outdent,indent,undo,redo,forecolor,backcolor,spellchecker,tablecontrols",
      theme_advanced_resizing : true,

      setup : function(ed) {
         //ed.onInit.add(function(ed) {
         //   ed.onKeyUp.dispatch();
         //}); 

         //ed.onKeyUp.add(function() {
         //   countChars();
         //});

         //ed.onPaste.add(function() {
         //});
      }
   });

}

function countChars()
{
     chars = tinyMCE.activeEditor.getContent();
     chars = $(chars).text();
     totalChars = chars.length;
     newLines = chars.match(/\r|\n/g); // searches for "\r" and "\n" chars.
     newLines = newLines ? newLines.length : 0;
        
     totalChars = totalChars - newLines;

     minLen = $('#minLen').text();
     charsLeft = minLen - totalChars;
     if (charsLeft < 0) {
        charsLeft = 0;
     }
     
     $('#charsLeft').text(charsLeft);
}

</script>

<?php
   $this->headLink()->appendStylesheet($coopSess->baseUrl.'/css/learningOutcome.css'); 
   echo $this->headLink();
?>