<?php
   $coopSess = new Zend_Session_Namespace('coop');
   $this->headScript()->appendFile($coopSess->baseUrl.'/js/tinymce/jscripts/tiny_mce/tiny_mce.js');
   echo $this->headScript();


   echo $this->message;

   $form = $this->form;

   echo $form;
?>


<script type="text/javascript">
   $('document').ready(function() {

      //$("#learningOutcomeReport").bind("submit", function() {
      //   if (!confirm("")) {
      //      return false;
      //   }
      //});

      $("[name=Submit]").live('click', function() {
         if (!confirm("Really submit?")) {
            return false;
         }
      });

   });



   tinyMCE.init({
        mode : "textareas",
        plugins : "spellchecker,searchreplace,paste,table",
        theme_advanced_resizing_min_height : 800,
        theme_advanced_resizing_max_width : 1020,

        // this file is a copy of the default content.css file in tinymce. font-size of 
        // the line containing "body, td, pre" was changed to give a different default font size.
        content_css : base + "/css/tinymce_custom_content.css",

        theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "pastetext,pasteword,|,bullist,numlist,|,outdent,indent,undo,redo,forecolor,backcolor,spellchecker,tablecontrols",
        theme_advanced_resizing : true
   });

</script>

<?php
   $this->headLink()->appendStylesheet($coopSess->baseUrl.'/css/learningOutcome.css'); 
   echo $this->headLink();
?>
