<h2> Student Assignment Status </h2>
<?php
   $form = $this->form;
   echo $form;
?>

<div class="asyncContainer">

</div>


<script>
   $('document').ready(function() {
      $('#Submit').live('click', function() {
         classId = $('#classes_id').val();
         //alert(classId);

         $.post(base + "/async/assignment-status-by-class", {'classId' : classId}, function(resp) {
            //alert('hi');
            $(".asyncContainer").empty();
            $(".asyncContainer").append(resp);

         });
      });
   });

</script>
