<?php
   $assigns = $this->assignments;

   $coopSess = new Zend_Session_Namespace('coop');

   $as = new My_Model_Assignment();

   $curSem = $coopSess->currentSemId;
   $curClass = $coopSess->currentClassId;
   $username = $coopSess->username;

   $funcs = new My_Funcs();



   $chk['semesters_id'] = $curSem;
   $chk['classes_id'] = $curClass;
   $chk['username'] = $username;
   $onclick = "return true";
   $isDisabled = "enabled";

   $url = $this->url(array('controller' => 'as'))

?>


<ul>
   <?php 
      $onclick = "return true";
      $isDisabled = "enabled";
      $assignId = $as->getResumeId();
      $assignment = $as->getAssignment($assignId);
      $due = $funcs->formatDateOut($assignment['due_date']);
      $chk['assignments_id'] = $assignId;
      if ( $as->isSubmitted($chk) === true || $as->isDue($assignId) ) { 
         $onclick = "return false";
         $isDisabled = "disabled";
      } 
    ?>

   <li><a onclick="<?php echo $onclick ?>" class="regText <?php echo $isDisabled?>" href='<?php echo $this->url(array('controller'=>'assignment',
                         'action'=>'resume'), null, true) ?>'> Resume </a> | due: <?php echo $due ?> </li><br />
   
   <?php 
      $onclick = "return true";
      $isDisabled = "enabled";
      $assignId = $as->getCoverLetterId();
      $assignment = $as->getAssignment($assignId);
      $due = $funcs->formatDateOut($assignment['due_date']);
      $chk['assignments_id'] = $assignId;
      if ( $as->isSubmitted($chk) === true || $as->isDue($assignId) ) { 
         $onclick = "return false";
         $isDisabled = "disabled";
      } 
    ?>

   <li><a onclick="<?php echo $onclick ?>" class="regText <?php echo $isDisabled?>" href='<?php echo $this->url(array('controller'=>'assignment',
                         'action'=>'cover-letter'), null, true) ?>'> Cover Letter </a> | due: <?php echo $due ?> </li><br />

   <?php 
      $onclick = "return true";
      $isDisabled = "enabled";
      $assignId = $as->getStuInfoId();
      //die($assignId);
      $assignment = $as->getAssignment($assignId);
      $due = $funcs->formatDateOut($assignment['due_date']);
      if ( $as->isDue($assignId) ) { 
         $onclick = "return false";
         $isDisabled = "disabled";
      } 
    ?>

   <li><a onclick="<?php echo $onclick ?>" class="regText <?php echo $isDisabled?>" href='<?php echo $this->url(array('controller'=>'form',
                         'action'=>'student-info-show'), null, true) ?>'> Student Information Sheet </a> | due: <?php echo $due ?>  </li><br />


   <?php 
      $onclick = "return true";
      $isDisabled = "enabled";
      $assignId = $as->getMidtermId();
      $assignment = $as->getAssignment($assignId);
      $due = $funcs->formatDateOut($assignment['due_date']);
      $chk['assignments_id'] = $assignId;
      if ( $as->isSubmitted($chk) === true || $as->isDue($assignId) ) { 
         $onclick = "return false";
         $isDisabled = "disabled";
      } 
    ?>

   <li><a onclick="<?php echo $onclick ?>" class="regText <?php echo $isDisabled?>" href='<?php echo $this->url(array('controller'=>'assignment',
                         'action'=>'midterm-report'), null, true) ?>'> Midterm Report </a> | due: <?php echo $due ?> </li><br />

   <?php 
      $onclick = "return true";
      $isDisabled = "enabled";
      $assignId = $as->getLearningOutcomeId();
      $assignment = $as->getAssignment($assignId);
      $due = $funcs->formatDateOut($assignment['due_date']);
      $chk['assignments_id'] = $assignId;
      if ( $as->isSubmitted($chk) === true || $as->isDue($assignId) ) { 
         $onclick = "return false";
         $isDisabled = "disabled";
      } 
    ?>

   <li><a onclick="<?php echo $onclick ?>" class="regText <?php echo $isDisabled?>" href='<?php echo $this->url(array('controller'=>'assignment',
                         'action'=>'learning-outcome'), null, true) ?>'> Learning Outcome Report </a> | due: <?php echo $due ?> </li><br />

   <?php 
      $onclick = "return true";
      $isDisabled = "enabled";
      $assignId = $as->getStudentEvalId();
      $assignment = $as->getAssignment($assignId);
      $due = $funcs->formatDateOut($assignment['due_date']);
      $chk['assignments_id'] = $assignId;
      if ( $as->isSubmitted($chk) === true || $as->isDue($assignId) ) { 
         $onclick = "return false";
         $isDisabled = "disabled";
      } 
    ?>

   <li><a onclick="<?php echo $onclick ?>" class="regText <?php echo $isDisabled?>" href='<?php echo $this->url(array('controller'=>'assignment',
                         'action'=>'student-eval'), null, true) ?>'> Student's Evaluation </a> | due: <?php echo $due ?> </li><br />

   <?php
      //$assignId = $as->getSupervisorEvalId();
      //$assignment = $as->getAssignment($assignId);
      //$due = $funcs->formatDateOut($assignment['due_date']);
   ?>

   <!-- <li><a class="regText" href='<?php echo $this->url(array('controller'=>'assignment',
                         'action'=>'supervisor-eval'), null, true) ?>'> Supervisor's Evaluation </a> | due: <?php echo $due ?></li><br /> -->
</ul>
