<h2> Manage Assignments </h2>
<?php
   
   $assigns = $this->assignments;

   $url = $this->url(array('controller' => 'assignment', 'action' => 'properties'));

   $editUrl = $this->url(array('controller' => 'assignment', 'action' => 'edit-duedate'));
   $extendUrl = $this->url(array('controller' => 'assignment', 'action' => 'extend-duedate'));

?>

<a class="regText" href="<?php echo $editUrl ?>"> Edit due dates </a><br /><br />
<a class="regText" href="<?php echo $extendUrl ?>"> Extend due date </a><br /><br /><br />

<table class="assignmentList">

   <?php foreach ($assigns as $as) { ?>

      <tr>

         <td>  <?php echo $as['assignment'] ?> </td>

         <?php
            //echo $as['assignment_num'];
            // Student and Employer evaluations need to have a class chosen before going to 
            // properties, so change the url for those assignments.
            if ($as['assignment_num'] === '5') {
               $url = $this->url(array('controller' => 'assignment', 'action' => 'student-eval-choose-class'));
            } else if ($as['assignment_num'] === '6') {
               $url = $this->url(array('controller' => 'assignment', 'action' => 'student-eval-choose-class'));
            }
         ?>

         <td> <a class="editLink" href="<?php echo $url . '?id=' . $as['id'] ?>">  Properties </a> </td>

      </tr>

   <?php } ?>


</table>
