<?php
   $assigns = $this->assignments;

   $coopSess = new Zend_Session_Namespace('coop');

   $as = new My_Model_Assignment();

   $chk['semesters_id'] =  $coopSess->currentSemId;
   $chk['classes_id'] =  $coopSess->currentClassId;
   $chk['username'] =  $coopSess->username;

   $onclick = "return true";
   $isDisabled = "enabled";

   $url = $this->url(array('controller' => 'as'))

?>


<ul>

   <?php 
      $onclick = "return true";
      $isDisabled = "enabled";
      $assignId = $as->getStuInfoId();
      if ( $as->isDue($assignId) ) { 
         $onclick = "return false";
         $isDisabled = "disabled";
      } 
    ?>

   <li><a onclick="<?php echo $onclick ?>" class="regText <?php echo $isDisabled?>" href='<?php echo $this->url(array('controller'=>'form',
                         'action'=>'student-info-show'), null, true) ?>'> Student Information Sheet </a></li><br />


   <li><a class="regText" href='<?php echo $this->url(array('controller'=>'form',
                         'action'=>'coop-agreement-show'), null, true) ?>'> Cooperative Agreement Form </a></li><br />

   <?php 
      $onclick = "return true";
      $isDisabled = "enabled";
      $assignId = $as->getMidtermId();
      $chk['assignments_id'] = $assignId;
      if ( $as->isSubmitted($chk) === true || $as->isDue($assignId) ) { 
         $onclick = "return false";
         $isDisabled = "disabled";
      } 
    ?>

   <li><a onclick="<?php echo $onclick ?>" class="regText <?php echo $isDisabled?>" href='<?php echo $this->url(array('controller'=>'assignment',
                         'action'=>'midterm-report'), null, true) ?>'> Midterm Report </a></li><br />

</ul>
