<?php
   
   $assigns = $this->assignments;

   $url = $this->url(array('controller' => 'assignment', 'action' => 'properties'));

   $editUrl = $this->url(array('controller' => 'assignment', 'action' => 'edit-duedate'));

?>

<a class="regText" href="<?php echo $editUrl ?>"> Edit due dates </a><br /><br /><br />

<table class="assignmentList">

   <?php foreach ($assigns as $as) { ?>

      <tr>

         <td>  <?php echo $as['assignment'] ?> </td>

         <td> <a class="editLink" href="<?php echo $url . '?id=' . $as['id'] ?>">  Properties </a> </td>

      </tr>

   <?php } ?>


</table>
