<h2> Midterm Report </h2>

<?php
   $coopSess = new Zend_Session_Namespace('coop');
   echo $this->headScript()->appendFile($coopSess->baseUrl . '/js/views/assignment/midterm-report.js');

   $form = $this->form;

   echo $this->message;

   echo $form;


?>

<script type="text/javascript">
$(document).ready(function() {

   $("#finalSubmit").live('click', function() {
      if (!confirm("Really submit?")) {
         return false;
      }
   });


});

</script>