<?php
   
   $assign = $this->assign;
   $dueDateUrl = $this->url(array('controller' => 'assignment', 'action' => 'edit-duedate'));
   if ($assign['assignment_num'] === '5') {
      $addAction = "add-question-student-eval";
      $editAction = "edit-question-student-eval";
      $deleteAction = "delete-question-student-eval";
   } else {
      $addAction = "add-question";
      $editAction = "edit-questions";
      $deleteAction = "delete-question";
   }
   $editQuestsUrl = $this->url(array('controller' => 'assignment', 'action' => $editAction));
   $addQuestUrl = $this->url(array('controller' => 'assignment', 'action' => $addAction));
   $delQuestUrl = $this->url(array('controller' => 'assignment', 'action' => $deleteAction));

   echo $this->message;

?>

<h2> <?php echo $assign['assignment'] ?> </h2>

<!-- <a href='<?php echo "$dueDateUrl?id=".$assign['id'] ?>'> Edit Due Date </a> <br /> <br /> -->

<?php if ($assign['questions_editable']) { ?>

    <a class="regText" href='<?php echo "$editQuestsUrl?id=" . $assign['id'] ?> '> Edit Questions </a><br /><br />
    <a class="regText" href='<?php echo "$addQuestUrl?id=" . $assign['id'] ?> '> Add a Question </a><br /><br />
    <a class="regText" href='<?php echo "$delQuestUrl?id=" . $assign['id'] ?> '> Delete a Question </a><br /><br />

<?php } ?>

<p class="regText"> Due date: <?php echo $assign['due_date'] ?> </p>
