<?php
   
   $assign = $this->assign;
   $dueDateUrl = $this->url(array('controller' => 'assignment', 'action' => 'edit-duedate'));
   $editQuestsUrl = $this->url(array('controller' => 'assignment', 'action' => 'edit-questions'));
   $addQuestUrl = $this->url(array('controller' => 'assignment', 'action' => 'add-question'));

   echo $this->message;

?>

<h2> <?php echo $assign['assignment'] ?> </h2>

<!-- <a href='<?php echo "$dueDateUrl?id=".$assign['id'] ?>'> Edit Due Date </a> <br /> <br /> -->

<?php if ($assign['questions_editable']) { ?>

    <a class="regText" href='<?php echo "$editQuestsUrl?id=" . $assign['id'] ?> '> Edit Questions </a><br /><br />
    <a class="regText" href='<?php echo "$addQuestUrl?id=" . $assign['id'] ?> '> Add Question </a><br /><br />

<?php } ?>

<p class="regText"> Due date: <?php echo $assign['due_date'] ?> </p>
