
<?php
$coopSess = new Zend_Session_Namespace('coop');
$this->headScript()->appendFile($coopSess->baseUrl.'/js/tinymce/jscripts/tiny_mce/tiny_mce.js');
//$this->headScript()->appendFile($coopSess->baseUrl.'/xinha/XinhaCore.js');
echo $this->headScript();

$this->pageTitle = "Resume";

echo $this->message;

$form = $this->form;
echo $form;
?>

<script type="text/javascript">
$(document).ready(function() {
   $("#finalSubmit").live('click', function() {
      if (!confirm("Really submit?")) {
         return false;
      }
   });


   /*
   tinyMCE.init({
        mode : "textareas",
        plugins : "spellchecker,searchreplace,paste,table",
        theme_advanced_resizing_min_height : 800,
        theme_advanced_resizing_max_width : 1020,

        // this file is a copy of the default content.css file in tinymce. font-size of 
        // the line containing "body, td, pre" was changed to give a different default font size.
        content_css : base + "/css/tinymce_custom_content.css",

        theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,fontselect,fontsizeselect",
        theme_advanced_buttons2 : "pastetext,pasteword,|,bullist,numlist,|,outdent,indent,undo,redo,forecolor,backcolor,spellchecker,tablecontrols",
        theme_advanced_resizing : true,

        setup : function(ed) {
           //ed.onInit.add(function(ed) {
           //   ed.onKeyUp.dispatch();
           //}); 

           //ed.onKeyUp.add(function() {
           //   countChars();
           //});

           //ed.onPaste.add(function() {
           //});
        }
   });
   */





   xinha_editors = null;
   xinha_init    = null;
   xinha_config  = null;
   xinha_plugins = null;

   xinha_init = xinha_init ? xinha_init : function()
   {
       xinha_editors = xinha_editors ? xinha_editors :
       [
          'static_tasks-resume'
       ];

       xinha_plugins = xinha_plugins ? xinha_plugins :
       [
        'CharacterMap',
        'ContextMenu',
        'ListType',
        'Stylist',
        'Linker',
        'SuperClean',
        'TableOperations'
       ];
       
       // THIS BIT OF JAVASCRIPT LOADS THE PLUGINS, NO TOUCHING  :)
       if(!Xinha.loadPlugins(xinha_plugins, xinha_init)) return;

       xinha_config = xinha_config ? xinha_config() : new Xinha.Config();
         
       //this is the standard toolbar, feel free to remove buttons as you like
       xinha_config.toolbar =
       [
         ["popupeditor"],
         ["separator","formatblock","fontname","fontsize","bold","italic","underline","strikethrough"],
         ["separator","forecolor","hilitecolor","textindicator"],
         ["separator","subscript","superscript"],
         ["linebreak","separator","justifyleft","justifycenter","justifyright","justifyfull"],
         ["separator","insertorderedlist","insertunorderedlist","outdent","indent"],
         ["separator","inserthorizontalrule","createlink","insertimage","inserttable"],
         ["linebreak","separator","undo","redo","selectall","print"], (Xinha.is_gecko ? [] : ["cut","copy","paste","overwrite","saveas"]),
         ["separator","killword","clearfonts","removeformat","toggleborders","splitblock","lefttoright", "righttoleft"],
         ["separator","htmlmode","showhelp","about"]
       ];

       xinha_editors   = Xinha.makeEditors(xinha_editors, xinha_config, xinha_plugins);
       Xinha.startEditors(xinha_editors);
  
  
   }
   Xinha._addEvent(window,'load', xinha_init);

});

_editor_url = "/xinha/";   // (preferably absolute) URL (including trailing slash) where Xinha is installed
_editor_lang = "en";       // And the language we need to use in the editor.
_editor_skin = "silva";    // If you want use a skin, add the name (of the folder) here
_editor_icons = "classic"; // If you want to use a different iconset, add the name (of the folder, under the `iconsets` folder) here


</script>

<script type="text/javascript" src="/xinha/XinhaCore.js"></script>