<?php
$coopSess = new Zend_Session_Namespace('coop');
$this->headScript()->appendFile($this->baseUrl() . '/js/views/assignment/timesheet.js');
echo $this->headScript();

$this->pageTitle = "Student Time Sheet";
$form = $this->form;

echo $form;
?>


<script type="text/javascript">
   
$(document).ready(function() {

   // Add confirmation to submit button
   $("#finalSubmit").live('click', function() {
      if (!confirm("Really submit?")) {
         return false;
      }
   });


});

</script>
