<style>
   #form-meta-data {
      margin-bottom: 30px;
      font-size: 16px;
   }
</style>

<?php
$coopSess = new Zend_Session_Namespace('coop');
$this->headScript()->appendFile($this->baseUrl() . '/js/views/assignment/timesheet.js');
echo $this->headScript();

$this->pageTitle = "Student Time Sheet";
echo $this->message;

if ($coopSess->role === 'coordinator') {
   echo "<div id=form-meta-data>";
   echo $this->form->studentName . "<br />";
   echo $this->form->class . "<br />";
   echo $this->form->semester . "<br />";
   echo "</div>";
}

$form = $this->form;

echo $form;
?>


<script type="text/javascript">
   
$(document).ready(function() {
    $("#pdfSubmit").live('click', function() {
        $("#studentEvalForm").attr('action', base + "/pdf/timesheet");

    });

   // Add confirmation to submit button
   $("#finalSubmit").live('click', function() {
      if (!confirm("Really submit?")) {
         return false;
      }
   });


});

</script>
