<?php 
   $coopSess = new Zend_Session_Namespace('coop');
   $this->headTitle('Cooperative Education');
   $this->headTitle()->setSeparator(' - ');
   $this->headTitle($this->pageTitle);
   
   echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
   <?php 
      echo $this->headTitle();
      
      //echo $this->headTitle($this->pageTitle);
      $this->headLink()->appendStylesheet($coopSess->baseUrl.'/css/screen.css', 'screen, projection'); 
      $this->headLink()->appendStylesheet($coopSess->baseUrl.'/css/print.css', 'print'); 
      $this->headLink()->appendStylesheet($coopSess->baseUrl.'/css/main.css'); 
      $this->headLink()->appendStylesheet($coopSess->baseUrl.'/css/ie.css', 'screen, projection', 'IE'); 
      echo $this->headLink();
   ?>
</head>
<body>
   <?php
      echo "<div id=main>";
      
      echo "<div id=innerMain>";
      
      // Start Header.
      echo "<div id='header'>";
      echo    "<div id=headerUpperRight>";
      echo       $coopSess->fname." ".$coopSess->lname."<br />";
      //echo       $coopSess->uhinfo['name']."<br />";
      
      if ($coopSess->role != 'none' || !empty($coopSess->uhinfo)) {
         echo "<a href='".$this->url(array('controller'=>'auth','action'=>'logout'))."'> Logout </a>";
      } else {
         echo "<a href='".$this->url(array('controller'=>'auth','action'=>'cas'))."'> Login (CAS) </a>";
      }

      //echo       "<a class='logout' href='".$this->url(array('controller'=>'auth','action'=>'logout'))."'>Logout </a>";
      echo    "</div>";
      echo    "<div id=headerMain>";
      echo       "<h2> Header </h2>";
      echo    "</div>";
      echo "</div>";
      // End Header.
      
      // Start main nav
      echo "<div id=leftNav>";
      echo "<ul>";

      // COORDINATOR VIEW

      if ($coopSess->role == 'coordinator') {
         echo    "<li><a href='".$this->url(array('controller'=>'syllabus',
                             'action'=>'listall'))."'> Class syllabuses </a></li> <br />";

         echo    "<li><a href='".$this->url(array('controller'=>'user',
                             'action'=>'new'))."'> Add student </a></li> <br />";
         

         //echo    "<li><a href='".$this->url(array('controller'=>'user',
         //             'action'=>'list-unenrolled'))."'> Enroll students </a></li> <br />";

         echo    "<li><a href='".$this->url(array('controller'=>'user',
                      'action'=>'history-search'))."'> Student co-op history </a></li> <br />";

      // USER VIEW

      } else if ($coopSess->role == 'user') {
         echo    "<li><a href=".$this->url(array('controller'=>'syllabus',
                                           'action'=>'view')).">Syllabus</a></li> <br />";

         echo    "<li><a href='".$this->url(array('controller'=>'contract',
                             'action'=>'new'))."'> Co-op Agreement Form </a></li> <br />";

         echo    "<li><a href='".$this->url(array('controller'=>'form',
                               'action'=>'student-info-show'))."'> Student Information Sheet </a></li>";
      } else if ($coopSess->role == 'supervisor') {

         echo    "<li><a href='".$this->url(array('controller'=>'contract',
                             'action'=>'new'))."'> Co-op Agreement Form </a></li> <br />";

      }

      echo "</ul>";
      echo "</div>";
      // End main nav
      
      // Start content
      echo "<div id=content>";
      echo "<h2>$this->pageTitle</h2>";
      
      echo $this->layout()->content;
      
      echo "</div>";
      // End content
      
      // Start footer
      echo "<div id='footer'>";
      echo "<h1> Footer </h1>";
      echo "<div>";
      // End footer
      
      echo "</div>";
      // End inner main div
      
      echo "</div>";
      // End main div
   ?>
</body>
</html>

  