<?php
   $coopSess = new Zend_Session_Namespace('coop');
   
   echo "<ul>";

   // COORDINATOR LINKS

   //if ($coopSess->role == 'coordinator') {
      echo    "<li><a href='".$this->url(array('controller'=>'syllabus',
                          'action'=>'listall'), null, true)."'> Class syllabuses </a></li> <br />";

      echo    "<li><a href='".$this->url(array('controller'=>'user',
                          'action'=>'new'), null, true)."'> Add student </a></li> <br />";
      

      //echo    "<li><a href='".$this->url(array('controller'=>'user',
      //             'action'=>'list-unenrolled'))."'> Enroll students </a></li> <br />";

      echo    "<li><a href='".$this->url(array('controller'=>'user',
                   'action'=>'searchstudent'), null, true)."'> Search student records </a></li> <br />";

      echo    "<li><a href='".$this->url(array('controller'=>'assignment',
                   'action'=>'submit'), null, true)."'> Submit an assignment </a></li> <br />";

      echo    "<li><a href='".$this->url(array('controller'=>'class',
                   'action'=>'listall'), null, true)."'> Coop class list </a></li> <br />";
   // STUDENT LINKS

   //} else if ($coopSess->role == 'user') {
      echo    "<li><a href=".$this->url(array('controller'=>'syllabus',
                                        'action'=>'view'), null, true).">Syllabus</a></li> <br />";

      echo    "<li><a href='".$this->url(array('controller'=>'contract',
                          'action'=>'new'), null, true)."'> Co-op Agreement Form </a></li> <br />";

      echo    "<li><a href='".$this->url(array('controller'=>'form',
                            'action'=>'student-info-show'), null, true)."'> Student Information Sheet </a></li><br />";
   //} else if ($coopSess->role == 'supervisor') {

      echo    "<li><a href='".$this->url(array('controller'=>'contract',
                          'action'=>'new'), null, true)."'> Co-op Agreement Form </a></li> <br />";

   //}

   echo "</ul>";
?>