<style>

    label {
        display: block;
    }

    #comment-form {
        margin-top: 100px;
    }

    #comment {
       height: 100px;
    }

    #student-select select option {
        padding: 0 0 7px;
    }

    #view-comments-button {
       margin-top: 20px;
    }

</style>

<?php
   $searchForm = $this->searchForm;
   $commentForm = $this->commentForm;
?>

<h2> Create a Comment </h2>

                <!-- Search Form -->
<h3> Search for a student to create a comment for </h3>
<form id="search-form">                
    <div style="float:left; margin-right:10px;">
        <label for="fname"> First name: </label>
        <?php echo $searchForm->fname ?>
    </div>

    <div style="float:left; margin-right: 10px;">
        <label for="lname"> Last name: </label>
        <?php echo $searchForm->lname ?>
    </div>

    <div style="float:left; margin-right: 20px;">
        <label for="username"> Username: </label>
        <?php echo $searchForm->username ?>
    </div>

    <div style="float:left; margin-top: 25px;">
        <button id="search-button"> Search </button>
    </div>

    <div style="clear:both"></div>
</form>

<br /><br /><hr />

                <!-- Comment Form -->
<div id="result-message"> </div>

<form id="comment-form" method="POST">
   
    
    <div id="student-select" style="float:left; margin-right: 30px;">
        <label for="student"> Select student: </label>
        <?php echo $commentForm->student ?>
    </div>
    <div style="float:left">
        <label for="comment"> Enter comment: </label>
        <?php echo $commentForm->comment ?>
    </div>

    <div style="float:left; margin-top: 115px;">
        <?php echo $commentForm->submit ?> 
    </div>
</form>
<div style="clear:both"></div>

<button id="view-comments-button">View comments for student</button>

<div id="comments-for-student">

</div>



<script type="text/javascript">
    $(document).ready(function() {
        $("#search-button").live('click', function() {
           formData = $("#search-form").toJSON(); 

           $.get(base + "/async/fetch-students-as-json", {'data' : formData}, function(resp) {
               //alert(resp);
               $("#comments-for-student").empty();
               students = resp;

               // Create options to populate student drop down.
               optionStr = "";
               $.each(students, function(key, user) {
                   optionStr += "<option value=" + user.username + ">" + user.lname + 
                       ", " + user.fname + " (" + user.username + ")</option>"
               })

               $("#student-select select").html(optionStr)

           }, 'json');

           return false;
        });

        $("#comment-form").submit(function() {
           form = $(this)
           data = {
              'student' : form.find("select#student").val(),
              'comment' : form.find("textarea#comment").val()
           }

           $.post(base + "/comments/new", { 'data' : data }, function(resp) {
              $("#result-message").html(resp)
              $("#view-comments-button").click()
              
              // Fade out the result message after 7 seconds.
              setTimeout(function(){
                 $("#result-message p").fadeOut("slow", function () {
                    $("#result-message p").remove();
                 })

              }, 7000) 
           })
             
           return false
        });

        $("#view-comments-button").live('click', function() {
           student = $("#student").val();
           $.get(base + "/comments/list", { 'student' : student }, function(resp) {
              $("#comments-for-student").empty().append(resp);
           })

           return false;
        });
        

        // FOR LIST.PHTML
        $(".edit-comment").live('click', function() {
           $(".cancel-update-button").click();
           commentText = $(this).parent("li").children("p").text();
  
           listItem = $(this).parent("li");
           children = listItem.html();
           //alert(commentText);
           listItem.html("<textarea name='comment'>" + commentText + "</textarea>");
           listItem.append("<button class='update-comment-button'> Update </button>");
           listItem.append("<button class='cancel-update-button'> Cancel </button>");
  
           return false;
  
        });
        
        
        $(".update-comment-button").live('click', function() {
           //comment['comment'] = listItem.children("textarea").val();
           //comment['id'] = listItem.attr("id");
  
           comment = {
              comment : listItem.children("textarea").val(),
              id      : listItem.attr("id")
           };
  
           //alert(comment.comment);
  
           $.post(base + "/comments/update", { 'comment' : comment }, function(resp) {
              $("#view-comments-button").click();
  
              return false;
           });
  
        });
        
        
        $(".cancel-update-button").live('click', function() {
           listItem.html(children);
        })


        $(".delete-comment").live('click', function() {
           if (confirm("Are you sure?")) {
              parentListItem = $(this).parent("li")
              comment = parentListItem.attr("id")
              
              $.post(base + "/comments/destroy", { 'comment' : comment }, function(resp) {
                 $("#view-comments-button").click()
              })
           }

           return false
        })
    });
</script>