<head>
   <?php $coopSess = new Zend_Session_Namespace('coop'); ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jquery.js') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jqplot/jquery.jqplot.min.js') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jqplot/plugins/jqplot.barRenderer.min.js') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jqplot/plugins/jqplot.categoryAxisRenderer.min.js') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jqplot/plugins/jqplot.pointLabels.min.js') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/views/reports/main.js') ?>
   <?php echo $this->headLink()->appendStylesheet($coopSess->baseUrl.'/js/jqplot/jquery.jqplot.css') ?>
   <?php echo $this->headLink()->appendStylesheet($coopSess->baseUrl.'/css/views/reports/main.css') ?>
</head>

<?php
   $forAllMajors = $this->forAllMajors;
   $byMajor = $this->byMajor;
   $reportPeriod = $this->reportPeriod;

?>

<style>
   #for-all-majors {
      margin-bottom: 100px;
   }

   /* for some reason, putting this in an external css file doesn't work */
   .jqplot-yaxis-tick {
      width: 110px;
      text-align: right;
   }

</style>

<h2 id='page-title'> Completion Rate Report </h2>
<h3 id="report-period"> <?php echo $reportPeriod ?> </h3>


<div id="report-container">

   <div id="legend">
      <table>
         <tr>
            <td> <div style="border: 7px solid rgb(234, 162, 40);"> </div> </td>
            <td> Completed Students </td>
         </tr>
         <tr>
            <td> <div style="border: 7px solid rgb(75, 178, 197);"> </div> </td>
            <td> Total Students </td>
         </tr>
      </table>
   </div>


   <div id="for-all-majors">
   </div>

   <div id="by-major">
   </div>
</div>

<script>
   $(document).ready(function() {

         forAllMajors = {}
         forAllMajors = <?php echo json_encode($forAllMajors); ?>;

         //var s1 = [forAllMajors.totalCount];
         //var s2 = [forAllMajors.completionCount];

         var s1 = [[forAllMajors.totalCount, 'All Majors']];
         var s2 = [[forAllMajors.completionCount, 'All Majors']];

         //var ticks = ["All Majors"];

         options = jqPlotDefaultOptions();
         options['title'] = 'For all Majors'
         //options['series'] = [{label:'Total Students'}, {label: 'Completed Students'}]

         plotForAll = $.jqplot('for-all-majors', [s1, s2], options) 


         // By Major.
         byMajor = <?php echo json_encode($byMajor); ?>;

         var s1 = []
         var s2 = []

         maxCount = 0
         $.each(byMajor.totalCount, function(key, val) {
            count = parseInt(val['count'])
            if (count > maxCount) {
               maxCount = count
            }
            s1.push([val['count'], val['major']])
         })

         $.each(byMajor.completionCount, function(key, val) {
            s2.push([val['count'], val['major']])
         })

         amountAboveThreshold = s1.length - 6
         amountAboveThreshold = (amountAboveThreshold < 0) ? 0 : amountAboveThreshold

         $('#by-major').height(300 + (amountAboveThreshold * 50))

         options['title'] = "By Major"
         options['axes']['xaxis']['max'] = Math.round((maxCount + 10) / 10) * 10

         plotByMajor = $.jqplot('by-major', [s1, s2], options) 

   })

function jqPlotDefaultOptions() {
   options = 
   {
      //title: 'a',
      seriesDefaults:{
          renderer:$.jqplot.BarRenderer,
          pointLabels: { show: true, location: 'e', edgeTolerance: -25 },
          rendererOptions: {
             barDirection: 'horizontal'
          }
      },
      axes: {
          // Use a category axis on the x axis and use our custom ticks.
          xaxis: {
             min: 0,
             tickOptions: { formatString: '%d' }
          },
          yaxis: {
             renderer: $.jqplot.CategoryAxisRenderer
          }
      }
   }
   return options
}
</script>