<head>
   <?php $coopSess = new Zend_Session_Namespace('coop'); ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jquery.js') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jqplot/jquery.jqplot.min.js') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jqplot/plugins/jqplot.barRenderer.min.js') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jqplot/plugins/jqplot.categoryAxisRenderer.min.js') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jqplot/plugins/jqplot.pointLabels.min.js') ?>
   <?php echo $this->headLink()->appendStylesheet($coopSess->baseUrl.'/js/jqplot/jquery.jqplot.css') ?>
</head>

<?php
   require 'libchart/classes/libchart.php';
   $forAllMajors = $this->forAllMajors;
   $byMajor = $this->byMajor;
   $reportPeriod = $this->reportPeriod;

?>

<style>
   #report-container {
      margin-left: 30px;
      margin-right: 30px;
   }

   div#legend {
      margin-bottom: 50px;
   }

   #for-all-majors {
      width: 25%;
      margin-bottom: 100px;
   }

   #page-title, #report-period {
      text-align: center;
   }

</style>

<h2 id='page-title'> Completion Rate Report </h2>
<h3 id="report-period"> <?php echo $reportPeriod ?> </h3>


<div id="report-container">

   <div id="legend">
      <table>
         <tr>
            <td> <div style="border: 7px solid rgb(75, 178, 197);"> </div> </td>
            <td> Total Students </td>
         </tr>
         <tr>
            <td> <div style="border: 7px solid rgb(234, 162, 40);"> </div> </td>
            <td> Completed Students </td>
         </tr>
      </table>
   </div>



   <div id="for-all-majors">
   </div>

   <div id="by-major">
   </div>
</div>

<script>
   $(document).ready(function() {

      forAllMajors = {}
      forAllMajors = <?php echo json_encode($forAllMajors); ?>;

      var s1 = [forAllMajors.totalCount];
      var s2 = [forAllMajors.completionCount];

      var ticks = ["All Majors"];

      options = 
         {
            title: 'For all Majors',
            seriesDefaults:{
                renderer:$.jqplot.BarRenderer,
                rendererOptions: {fillToZero: true},
                pointLabels: { show: true, location: 'n', edgeTolerance: -25 }
            },
            series:[
                {label:'Total Students'},
                {label:'Completed Students'}
            ],
            axes: {
                // Use a category axis on the x axis and use our custom ticks.
                xaxis: {
                    renderer: $.jqplot.CategoryAxisRenderer,
                    ticks: ticks
                },
                // Pad the y axis just a little so bars can get close to, but
                // not touch, the grid boundaries.  1.2 is the default padding.
                yaxis: {
                   min: 1000
                   //pad: 1.05
                }
            }
         }



      plotForAll = $.jqplot('for-all-majors', [s1, s2], options) 
      /*
         {
            title: 'For all Majors',
            seriesDefaults:{
                renderer:$.jqplot.BarRenderer,
                rendererOptions: {fillToZero: true},
                pointLabels: { show: true, location: 'n', edgeTolerance: -25 }
            },
            series:[
                {label:'Total Students'},
                {label:'Completed Students'}
            ],
            axes: {
                // Use a category axis on the x axis and use our custom ticks.
                xaxis: {
                    renderer: $.jqplot.CategoryAxisRenderer,
                    ticks: ticks
                },
                // Pad the y axis just a little so bars can get close to, but
                // not touch, the grid boundaries.  1.2 is the default padding.
                yaxis: {
                   min: 1000
                   //pad: 1.05
                }
            }
         })
         */


         byMajor = {}
         byMajor = <?php echo json_encode($byMajor); ?>;

         var s1 = []
         var s2 = []
         var ticks = [];

         $.each(byMajor.totalCount, function(key, val) {
            s1.push(val['count'])
            ticks.push(val['major'])
         })

         $.each(byMajor.completionCount, function(key, val) {
            s2.push(val['count'])
         })

         options['title'] = "By Major"
         options['axes']['xaxis']['ticks'] = ticks

         plotByMajor = $.jqplot('by-major', [s1, s2], options) 
         /*
            {
               title: 'By Major',
               seriesDefaults:{
                   renderer:$.jqplot.BarRenderer,
                   rendererOptions: {fillToZero: true},
                   pointLabels: { show: true, location: 'n', edgeTolerance: -25 }
               },
               series:[
                   {label:'Total Students'},
                   {label:'Completed Students'}
               ],
               axes: {
                   // Use a category axis on the x axis and use our custom ticks.
                   xaxis: {
                       renderer: $.jqplot.CategoryAxisRenderer,
                       ticks: ticks
                   },
                   // Pad the y axis just a little so bars can get close to, but
                   // not touch, the grid boundaries.  1.2 is the default padding.
                   yaxis: {
                      min: 1000
                      //pad: 1.05
                   }
               }
            })
            */

   })
</script>