<head>
   <?php $coopSess = new Zend_Session_Namespace('coop'); ?>
   <?php echo $this->headLink()->prependStylesheet($coopSess->baseUrl.'/css/ie.css', 'screen, projection', 'IE'); ?>
   <?php echo $this->headLink()->prependStylesheet($coopSess->baseUrl.'/css/print.css', 'print'); ?> 
   <?php echo $this->headLink()->prependStylesheet($coopSess->baseUrl.'/css/screen.css', 'screen, projection'); ?>
   <?php echo $this->headLink()->appendStylesheet($coopSess->baseUrl.'/css/views/reports/main.css') ?>
</head>
<?php
   $results = $this->results;
   $reportPeriod = $this->reportPeriod;
   $overAllEvalMap = array("1" => "Excellent", "2" => "Above Average", "3" => "Satisfactory", "4" => "Unsatisfactory");

   $currentRecord = array('username' => "", 'class_id' => '', 'semesters_id' => '');
?>
<style>
   #emp-satisfaction-report th,td {
      text-align: center;
      border: 1px solid;
      padding: 10px 3px 10px 3px;
   }
</style>

<h2 id='page-title'> Employer Satisfaction Report </h2>
<h3 id="report-period"> <?php echo $reportPeriod ?> </h3>

<div id="report-container">
   <table id="emp-satisfaction-report">
      <tr>
         <th> Last </th>
         <th> First </th>
         <th> Course </th>
         <th> Employer </th>
         <th> Comments </th>
         <th> Overall </th>
      </tr>

      <?php foreach ($results as $r) { ?>
      <!-- Only add a new row if it's not a duplicate record. -->
      <?php if ($currentRecord['username']     !== $r['username'] ||
                $currentRecord['class_id']     !== $r['class_id'] ||
                $currentRecord['semesters_id'] !== $r['semesters_id']) { ?>
                    
         <!-- Set the new current record -->
         <?php 
            $currentRecord['username']     = $r['username'];
            $currentRecord['class_id']     = $r['class_id'];
            $currentRecord['semesters_id'] = $r['semesters_id']
         ?>

         <tr>
            <td><?php echo $r['lname'] ?></td>
            <td><?php echo $r['fname'] ?></td>
            <td><?php echo $r['class_name'] ?></td>

            <!-- Collect the current record's answer_text's for the supervisor eval. -->
            <?php $evalValues = array() ?>
            <?php foreach ($results as $r2) { ?>
               <?php if ($currentRecord['username']     === $r2['username'] && 
                         $currentRecord['class_id']     === $r2['class_id'] && 
                         $currentRecord['semesters_id'] === $r2['semesters_id']) { ?>
                  <?php $evalValues[] =  ($r2['static_question'] === "overall_eval") ? $overAllEvalMap[$r2['answer_text']] : $r2['answer_text'] ?>
               <?php } ?>
            <?php } ?>

            <!-- If evalValues is 3, that means this record submitted the eval and has values.
                 Otherwise, just add 3 blank <td> -->
            <?php if (count($evalValues) === 3) { ?>
               <?php foreach($evalValues as $v) { ?>
                  <td><?php echo (trim($v) === "") ? "N/A" : $v ?></td>
               <?php } ?>
            <?php } else { ?>
               <td> N/A </td>
               <td> N/A </td>
               <td> N/A </td>
            <?php } ?>
         </tr>

      <?php } ?>
      <?php } ?>
   </table>
</div>