<?php
   $form = $this->form
?>

<style>
   #left {
      float: left;
      margin-right: 60px;
   }

   #right {
      float: left;
   }

</style>

<form action="<?php echo $form->getAction() ?>" method="POST" target="_blank">
   <?php echo $form->report ?> <br />

   <div id='left'>
      <?php echo $form->semesters_id ?>
      <?php echo $form->bySemester ?> <br />
   </div>

   <div id="right">
      <?php echo $form->year ?>
      <?php echo $form->byYear ?>
   </div>
</form>