<head>
   <?php $coopSess = new Zend_Session_Namespace('coop'); ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jquery.js') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jqplot/jquery.jqplot.min.js') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jqplot/plugins/jqplot.barRenderer.min.js') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jqplot/plugins/jqplot.categoryAxisRenderer.min.js') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jqplot/plugins/jqplot.pointLabels.min.js') ?>
   <?php echo $this->headLink()->appendStylesheet($coopSess->baseUrl.'/js/jqplot/jquery.jqplot.css') ?>
   <?php echo $this->headLink()->appendStylesheet($coopSess->baseUrl.'/css/views/reports/main.css') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/views/reports/main.js') ?>
</head>

<?php
   $studentsPerMajor = $this->studentsPerMajor;
   $studentsPerClass = $this->studentsPerClass;
   $reportPeriod     = $this->reportPeriod;
?>

<style>
   #students-per-major {
      margin-top: 100px;
      margin-bottom: 100px;
   }

   #students-per-class {
   }

   /* for some reason, putting this in an external css file doesn't work */
   .jqplot-yaxis-tick {
      width: 110px;
      text-align: right;
   }

</style>

<h2 id='page-title'> Student Demographic Report </h2>
<h3 id="report-period"> <?php echo $reportPeriod ?> </h3>

<div id="report-container">
   <div id="test-plot">
   </div>

   <div id="students-per-major">
   </div>

   <div id="students-per-class">
   </div>
</div>

<script type="text/javascript">
$(document).ready(function() {

   options = jqPlotDefaultOptions();

/*
   // Testing
   s1 = []
   for (i = 0; i < 17; i++) {
      s1.push([5, i+1])
   }

   foo = s1.length - 6
   foo = (foo < 0) ? 0 : foo

   $('#test-plot').height(300 + (foo * 50))


   //s1 = [[5,1], [5,2], [5,3], [5,4], [5,5], [5,6]]
   testPlot = $.jqplot('test-plot', [s1], options) 


   //$('#test-plot').replaceWith("<div id='test-plot'> </div")
   //$('#test-plot').height($('#test-plot .jqplot-yaxis').height() + 550)
   ////testPlot.replot()
   //testPlot = $.jqplot('test-plot', [s1], options) 

   // End Testing
   */



   options['series'] = [{label: 'Number of Students'}]

   studentsPerMajor = <?php echo json_encode($studentsPerMajor); ?>;
   options['title'] = "Number of Students per Major"
   genDemographicGraph(studentsPerMajor, 'major', 'students-per-major', options)


   studentsPerClass = <?php echo json_encode($studentsPerClass); ?>;
   options['title'] = "Number of Students per Class"
   genDemographicGraph(studentsPerClass, 'class', 'students-per-class', options)

   //$('#students-per-class').height($('#students-per-class .jqplot-yaxis').height() + 450)
   //$('#students-per-class').data("jqplot").replot

});

function jqPlotDefaultOptions() {
   options = 
   {
      //title: 'a',
      seriesDefaults:{
          renderer:$.jqplot.BarRenderer,
          pointLabels: { show: true, location: 'e', edgeTolerance: -25 },
          rendererOptions: {
             barDirection: 'horizontal'
          }
      },
      axes: {
          // Use a category axis on the x axis and use our custom ticks.
          xaxis: {
             min: 0,
             tickOptions: { formatString: '%d' }
          },
          yaxis: {
             renderer: $.jqplot.CategoryAxisRenderer,
             tickOptions: { }
          }
      }
   }
   return options
}


function genDemographicGraph(reportData, group, div, opts) 
{
   var s1 = []

   maxCount = 0
   $.each(reportData.reverse(), function(key, val) {
      count = parseInt(val['count'])
      if (count > maxCount) {
         maxCount = count
      }
      s1.push([val['count'], val[group]])
   })

   opts['axes']['xaxis']['max'] = Math.round((maxCount + 10) / 10) * 10

   amountAboveThreshold = s1.length - 6
   amountAboveThreshold = (amountAboveThreshold < 0) ? 0 : amountAboveThreshold

   $('#'+div).height(300 + (amountAboveThreshold * 50))

   plot = $.jqplot(div, [s1], opts) 

   //$('#'+div).height($('#'+div+" .jqplot-yaxis").height() + 450)
   //plot.replot()


}
</script>