<head>
   <?php $coopSess = new Zend_Session_Namespace('coop'); ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jquery.js') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jqplot/jquery.jqplot.min.js') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jqplot/plugins/jqplot.barRenderer.min.js') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jqplot/plugins/jqplot.categoryAxisRenderer.min.js') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/jqplot/plugins/jqplot.pointLabels.min.js') ?>
   <?php echo $this->headLink()->appendStylesheet($coopSess->baseUrl.'/js/jqplot/jquery.jqplot.css') ?>
   <?php echo $this->headLink()->appendStylesheet($coopSess->baseUrl.'/css/views/reports/main.css') ?>
   <?php echo $this->headScript()->appendFile($coopSess->baseUrl.'/js/views/reports/main.js') ?>
</head>

<?php
   $studentsPerMajor = $this->studentsPerMajor;
   $studentsPerClass = $this->studentsPerClass;
   $reportPeriod     = $this->reportPeriod;
?>

<style>
   /*
   #report-container {
      margin-left: 20px;
      margin-right: 100px;
   }
   */

   #students-per-major {
      margin-top: 100px;
      margin-bottom: 100px;
   }

</style>

<h2 id='page-title'> Student Demographic Report </h2>
<h3 id="report-period"> <?php echo $reportPeriod ?> </h3>

<div id="report-container">
   <div id="test-plot">
   </div>

   <div id="students-per-major">
   </div>

   <div id="students-per-class">
   </div>
</div>

<script type="text/javascript">
$(document).ready(function() {

   options = jqPlotDefaultOptions();

   options['series'] = [{label: 'Number of Students'}]

   studentsPerMajor = <?php echo json_encode($studentsPerMajor); ?>;
   options['title'] = "Number of Students per Major"
   genDemographicGraph(studentsPerMajor, 'major', 'students-per-major', options)


   studentsPerClass = <?php echo json_encode($studentsPerClass); ?>;
   options['title'] = "Number of Students per Class"
   genDemographicGraph(studentsPerClass, 'class', 'students-per-class', options)


});

function jqPlotDefaultOptions() {
   options = 
   {
      //title: 'a',
      seriesDefaults:{
          renderer:$.jqplot.BarRenderer,
          pointLabels: { show: true, location: 'e', edgeTolerance: -25 },
          rendererOptions: {
             barPadding: 190,
             barDirection: 'horizontal'
          }
      },
      axes: {
          // Use a category axis on the x axis and use our custom ticks.
          xaxis: {
             min: 0,
             tickOptions: { formatString: '%d' }
          },
          yaxis: {
             renderer: $.jqplot.CategoryAxisRenderer
          }
      }
   }
   return options
}


function genDemographicGraph(reportData, group, div, opts) 
{
   var s1 = []

   maxCount = 0
   $.each(reportData.reverse(), function(key, val) {
      count = parseInt(val['count'])
      if (count > maxCount) {
         maxCount = count
      }
      s1.push([val['count'], val[group]])
   })

   opts['axes']['xaxis']['max'] = Math.round((maxCount + 10) / 10) * 10

   $.jqplot(div, [s1], opts) 

}
</script>