<?php
   $form = $this->form;

   echo "<h2> Delete a coordinator </h2>";

   if ($this->success === true) {
      echo "<p class='success'> Coordinator has been deleted </p>";
   } else if ($this->success === false) {
      echo "<p class='error'> Deletion failed </p>";
   }


   echo $form;
?>


<script type="text/javascript">
   $('document').ready(function() {

      $("#delete-coord").bind("submit", function() {
         if (!confirm("Are you sure you want to delete this coordinator?")) {
            return false;
         }
      });

   });



</script>