<?php 
   $coopSess = new Zend_Session_Namespace('coop');
   $demoPromoUrl = $this->url(array('controller' => 'user', 'action' => 'demote-promote')); 
?>

<?php if ($coopSess->role === 'coordinator') { ?>
   <a id="promote" class="editLink" href='<?php echo "$demoPromoUrl?role=student-aid&username=".$this->username ?>'> MAKE STUDENT-AID </a> <br /><br />
<?php } ?>

<?php
   $form = $this->form;

   echo $form;
?>

<script type="text/javascript">
   $("#promote").live('click', function() {
      if (!confirm("Really make a student helper? Student will be dropped from all classes for the current semester.")) {
         return false;
      }
   });
</script>
