<?php
   $coords = $this->coords;
   $editUrl = $this->url(array('controller' => 'user', 'action' => 'edit-coord'));
   $addUrl = $this->url(array('controller' => 'user', 'action' => 'add-coord'));
   $delUrl = $this->url(array('controller' => 'user', 'action' => 'delete-coord'));
?>

<h2> Manage Coordinators </h2>


<p> <a class="regText" href="<?php echo $addUrl ?>"> Add coordinator</a> </p>
<p> <a class="regText" href="<?php echo $delUrl ?>"> Delete coordinator</a> </p>

<table id="coordList" class="stripe">

   <th> Name </th> <th> Number </th> <th> Email </th> <th> Fax </th>


   <?php foreach ($coords as $c) { ?>

      <tr>

         <td class="regText">
            <?php echo $c['fname'] . " " . $c['lname'] ?>

         </td>

         <td class="regText">
            <?php echo $c['home_phone'] ?>

         </td>

         <td class="regText">
            <?php echo $c['email'] ?>

         </td>
         
         <td class="regText">
            <?php echo $c['fax'] ?>

         </td>

         <td>
            <a class="editLink" href='<?php echo "$editUrl?username=".$c['username'] ?>'> EDIT </a>
         </td>
      </tr>

   <?php } ?>





</table>