<table class="padded">
<?php
   
   $users = $this->users;

   foreach ($users as $u) { 
      $enrollUrl = $this->url(array('action'=>'activate'));
      $enrollUrl .= "?users_id=".$u['users_id'].
              "&semesters_id=".$u['semesters_id'].
              "&classes_id=".$u['classes_id'];
?>
   <tr> 
      <td>
         <?php echo $u['fname'].' '.$u['lname']; ?> <br />
         <?php echo "(".$u['username'].")"; ?>
      </td> 
      <td> <?php echo $u['class']; ?> </td> 
      <td> 
         <a href="<?php echo $enrollUrl ?>"> Enroll </a>
      </td>

   </tr>
      

  <?php
  } 
  ?>

</table>
