<?php
// comment
   echo "<form id='searchform'>";
   echo "<table id='searchform-table'>";

   echo "<tr>";

   echo    "<td><b>Enter first name:</b><br />";
   echo    $this->form->fname."</td>";

   echo    "<td><b>Enter last name:</b><br />";
   echo    $this->form->lname."</td>";

   echo    "<td><b>Enter username:</b><br />";
   echo    $this->form->username."</td>";


   echo "</tr>";

   echo "<tr>";

   echo    "<td><b>Select coordinator:</b><br />";
   echo    $this->form->coordinator."</td>";

   echo    "<td><b>Select class:</b><br />";
   echo    $this->form->classes_id."</td>";

   echo    "<td><b>Select semester:</b><br />";
   echo    $this->form->semesters_id."<br /></td>";

   echo "</tr>";

   echo "<tr>";
   echo "<td>".$this->form->search. "</td>";
   echo "</tr>";

   echo "</table>";
   echo "<form><br /><br />";

   echo "<input type='hidden' id='resultFlag' value='' />";
   //echo $this->form;

   $url = $this->url(array('action' => 'home', 'controller' => 'pages', 'data' => 'hi'));

?>

<div class="buttonpanel">

   <button type="button" id="assignment-hist"> Assignment Record </button>

   <input type="button" onClick="location.href='<?php echo $url ?>'" value="link" />

   <input type="hidden" id="rec" data-rec="" />

</div><br />

<div id="asyncContainer">

</div>


<script type="text/javascript">
   $(document).ready(function(){

      base = '';


      $("#search").live('click', function() {

         search();

      });

      $("#assignment-hist").live('click', function() {

         data = getRec();
         alert(data);

         //temp = {'foo' : 'bar'};
         //alert(temp);
         $.post(base + "/async/submission-recs", {'data' : data}, function(resp) {

            $("#asyncContainer").empty();
            $("#asyncContainer").append(resp);

         });
      });

      $(".buttonpanel").hide();






      // FUNCTIONS
      
      function getRec() {
         if ( $("#searchresults-table").length > 0 ) {
            $("#rec").data("rec", "");
            rec = $("input[name=rec-choice]:checked").data('rec');
            $("#rec").data("rec", rec);
         } 
         data = $("#rec").data("rec");
         return data;
      }

      function search() {
         data = $("#searchform").toJSON();

         $.post(base + "/async/student-rec-search-result", {'data' : data}, function(resp) {

            $("#asyncContainer").empty();
            $("#asyncContainer").append(resp);

            // If there are results, show the button panel
            if ( $("#searchresults-table").length > 0) {
               $(".buttonpanel").show();
               //$("#resultFlag").val("success");
            // If no results, hide the button panel.
            } else {
               $(".buttonpanel").hide();
               //$("#resultFlag").val("");
            }

         });
      }

   });
</script>
