<?php
   echo "<form id='searchform'>";
   echo "<table id='searchform-table'>";

   echo "<tr>";

   echo    "<td><b>Enter first name:</b><br />";
   echo    $this->form->fname."</td>";

   echo    "<td><b>Enter last name:</b><br />";
   echo    $this->form->lname."</td>";

   echo    "<td><b>Enter username:</b><br />";
   echo    $this->form->username."</td>";


   echo "</tr>";

   echo "<tr>";

   echo    "<td><b>Select coordinator:</b><br />";
   echo    $this->form->coordinator."</td>";

   echo    "<td><b>Select class:</b><br />";
   echo    $this->form->classes_id."</td>";

   echo    "<td><b>Select semester:</b><br />";
   echo    $this->form->semesters_id."<br /></td>";

   echo "</tr>";

   echo "<tr>";
   echo "<td>".$this->form->search. "</td>";
   echo "</tr>";

   echo "</table>";
   echo "</form><br /><br />";

   echo "<input type='hidden' id='resultFlag' value='' />";
   //echo $this->form;

   $url = $this->url(array('action' => 'home', 'controller' => 'pages', 'data' => 'hi'));

?>

<div class="buttonpanel">

   <button type="button" id="assignment-hist"> Assignment Record </button>
   <button type="button" id="stuInfoSheet"> Student Information Sheet </button>

   <input type="hidden" id="stored-rec" data-rec="" />

</div><br /><br />

<div id="asyncContainer">

</div>


<script type="text/javascript">

   $(".buttonpanel").hide();

   $(document).ready(function(){


      $("#search").live('click', function() {

         search();

      });

      $("#assignment-hist").live('click', function() {

         data = getRec();

         //temp = {'foo' : 'bar'};
         $.post(base + "/async/submission-recs", {'data' : data}, function(resp) {

            $("#asyncContainer").empty();
            $("#asyncContainer").append(resp);

         });
      });


      $("#stuInfoSheet").live('click', function() {
         data = getRec();
         //alert(data);
         $.post(base + "/async/view-stu-info-sheet", {'data' : data}, function(resp) {

            $("#asyncContainer").empty();
            $("#asyncContainer").append(resp);

         });

      });







      // FUNCTIONS
      
      // Gets the record information of the selected record (username, class, semester) to
      // use in queries for different assignment information.
      function getRec() {
         // If the search results table (the table with student's name, class, semester, 
         // coordinator, etc.) is present, then the record information should be coming from
         // the selected record, so reset the stored record (#stored-rec) to that. 
         if ( $("#searchresults-table").length > 0 ) {
            $("#stored-rec").data("rec", "");
            rec = $("input[name=rec-choice]:checked").data('rec');
            $("#stored-rec").data("rec", rec);
         } 
         data = $("#stored-rec").data("rec");
         return data;
      }

      function search() {
         data = $("#searchform").toJSON();

         $.post(base + "/async/student-rec-search-result", {'data' : data}, function(resp) {

            $("#asyncContainer").empty();
            $("#asyncContainer").append(resp);

            // If there are results, show the button panel
            if ( $("#searchresults-table").length > 0) {
               $(".buttonpanel").show();
               //$("#resultFlag").val("success");
            // If no results, hide the button panel.
            } else {
               $(".buttonpanel").hide();
               //$("#resultFlag").val("");
            }

         });
      }

   });
</script>
