<h2> Search Student Records </h2>

<?php
   $coopSess = new Zend_Session_Namespace('coop');
   $this->headScript()->appendFile($coopSess->baseUrl.'/js/tinymce/jscripts/tiny_mce/tiny_mce.js');
   $this->headScript()->appendFile($coopSess->baseUrl.'/js/views/async/funcs.js');
   echo $this->headScript();

   echo "<form id='searchform'>";
   echo "<table id='searchform-table'>";

   echo "<tr>";

   echo    "<td><b>Enter first name:</b><br />";
   echo    $this->form->fname."</td>";

   echo    "<td><b>Enter last name:</b><br />";
   echo    $this->form->lname."</td>";

   echo    "<td><b>Enter username:</b><br />";
   echo    $this->form->username."</td>";


   echo "</tr>";

   echo "<tr>";

   echo    "<td><b>Select coordinator:</b><br />";
   echo    $this->form->coordinator."</td>";

   echo    "<td><b>Select class:</b><br />";
   echo    $this->form->classes_id."</td>";

   echo    "<td><b>Select semester:</b><br />";
   echo    $this->form->semesters_id."<br /></td>";

   echo "<td>".$this->form->search. "</td>";

   echo "</tr>";

   //echo "<tr>";
   //echo "<td>".$this->form->search. "</td>";
   //echo "</tr>";

   echo "</table>";
   echo "</form><br /><br />";

   echo "<input type='hidden' id='resultFlag' value='' />";
   //echo $this->form;

   $url = $this->url(array('action' => 'home', 'controller' => 'pages', 'data' => 'hi'));

?>

<div class="buttonpanel">

   <button type="button" id="assignment-hist"> Assignment Record </button>
   <button type="button" id="stuInfoSheet"> Student Information Sheet </button>
   <button type="button" class="midtermReport"> Midterm Report </button>
   <button type="button" class="learningOutcome"> Learning Outcome Report </button>
   <button type="button" class="studentEval"> Student Evaluation </button>
   <button type="button" class="supervisorEval" value="supervisorEval"> Supervisor Evaluation </button>

   <input type="hidden" id="stored-rec" data-rec="" />

</div><br /><br />

<div id="asyncContainer">

</div>


<script type="text/javascript">

   $(".buttonpanel").hide();

   $(document).ready(function(){


      $("#search").live('click', function() {
         $(".buttonpanel").show();

         search();

      });

      $("#assignment-hist").live('click', function() {

         data = getRec();

         if (data == "" || data == null) {
            return;
         }
         //temp = {'foo' : 'bar'};
         $.post(base + "/async/submission-recs", {'data' : data}, function(resp) {

            $("#asyncContainer").empty();
            $("#asyncContainer").append(resp);

         });
      });


      $("#stuInfoSheet").live('click', function() {
         data = getRec();
         if (data == "" || data == null) {
            return;
         }
         //alert(data);
         $.post(base + "/async/view-stu-info-sheet", {'data' : data}, function(resp) {

            $("#asyncContainer").empty();
            $("#asyncContainer").append(resp);

         });

      });

      $(".midtermReport").live('click', function() {
         data = getRec();
         if (data == "" || data == null) {
            return;
         }
         //alert(JSON.stringify(data,null,4));
         $.post(base + "/async/midterm-report", {'data' : data}, function(resp) {

            $("#asyncContainer").empty();
            $("#asyncContainer").append(resp);

         });

      });

      $(".studentEval").live('click', function() {
         data = getRec();
         if (data == "" || data == null) {
            return;
         }
         $.post(base + "/async/student-eval", {'data' : data}, function(resp) {

            $("#asyncContainer").empty();
            $("#asyncContainer").append(resp);
            $("#studentEvalForm").attr("value", "studentEval");
            //$(".highlighted").css('background-color', 'green');

         });

      });

      $(".supervisorEval").live('click', function() {
         data = getRec();
         if (data == "" || data == null) {
            return;
         }
         $.post(base + "/async/student-eval", {'data' : data, 'supervisorEval' : true}, function(resp) {

            $("#asyncContainer").empty();
            $("#asyncContainer").append(resp);
            $("#studentEvalForm").attr("value", "supervisorEval");
            //$(".highlighted").css('background-color', 'green');

         });

      });

      $(".learningOutcome").live('click', function() {
         data = getRec();
         if (data == "" || data == null) {
            return;
         }
         $.post(base + "/async/learning-outcome", {'data' : data}, function(resp) {

            $("#asyncContainer").empty();
            $("#asyncContainer").append(resp);
            tinyMCE.init({
                 mode : "exact",
                 elements : "report",
                 plugins : "spellchecker,searchreplace,paste,table",

                 // this file is a copy of the default content.css file in tinymce. font-size of 
                 // the line containing "body, td, pre" was changed to give a different default font size.
                 content_css : base + "/css/tinymce_custom_content.css",

                 theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,fontselect,fontsizeselect",
                 theme_advanced_buttons2 : "pastetext,pasteword,|,bullist,numlist,|,outdent,indent,undo,redo,forecolor,backcolor,spellchecker,tablecontrols",
                 theme_advanced_resizing : true
            });

         });

      });





      // FUNCTIONS
      
      // Gets the record information of the selected record (username, class, semester) to
      // use in queries for different assignment information.
      //function getRec() {
      //   // If the search results table (the table with student's name, class, semester, 
      //   // coordinator, etc.) is present, then the record information should be coming from
      //   // the selected record, so reset the stored record (#stored-rec) to that. 
      //   if ( $("#searchresults-table").length > 0 ) {
      //      $("#stored-rec").data("rec", "");
      //      rec = $("input[name=rec-choice]:checked").data('rec');
      //      $("#stored-rec").data("rec", rec);
      //   } 
      //   data = $("#stored-rec").data("rec");
      //   return data;
      //}
      

      function search() {
         data = $("#searchform").toJSON();

         $.post(base + "/async/student-rec-search-result", {'data' : data}, function(resp) {

            $("#asyncContainer").empty();
            $("#asyncContainer").append(resp);

            // If there are results, show the button panel
            if ( $("#searchresults-table").length > 0) {
               //$(".buttonpanel").show();
               //$("#resultFlag").val("success");
            // If no results, hide the button panel.
            } else {
               //$(".buttonpanel").hide();
               //$("#resultFlag").val("");
            }

         });
      }

   });
   

</script>
