<?php
   $coopSess = new Zend_Session_Namespace('coop');
   $this->headLink()->appendStylesheet($coopSess->baseUrl.'/css/jquery_datepicker/ui.all.css');

   echo $this->form;
?>

<div id="asyncContainer">


</div>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.5.3/jquery-ui.min.js"></script>
<script type="text/javascript">
   $("document").ready(function() {

      $("#search").live('click', function() {

         search();

      });


      function search() {
         data = $("#searchform").toJSON();

         //alert(data);

         $.post(base + "/async/view-logins", {'data' : data}, function(resp) {

            $("#asyncContainer").empty();
            $("#asyncContainer").append(resp);

            // If there are results, show the button panel
            if ( $("#searchresults-table").length > 0) {
               $(".buttonpanel").show();
               //$("#resultFlag").val("success");
            // If no results, hide the button panel.
            } else {
               $(".buttonpanel").hide();
               //$("#resultFlag").val("");
            }

         });
      }

      $("#startDate").datepicker({ showOn: 'button', buttonText: "Calendar", buttonImageOnly: true, buttonImage: base + "/images/x_office_calendar.png", constrainInput: false });
      $("#endDate").datepicker({ showOn: 'button', buttonText: "Calendar", buttonImageOnly: true, buttonImage: base + "/images/x_office_calendar.png", constrainInput: false });
   });

</script>