<style>
    #ext-duedates {
        width: 60%;
    }
    
    #ext-duedates tr th,td {
        font-size: 15px;
        padding: 10px 0 10px 0;
    }


</style>

<h2> Extended Due Dates </h2>

<?php
   $extDuedates = $this->extDuedates;
   $majors = $this->majors;

   $deleteUrl = array("controller" => "user", "action" => "delete-extended-duedate");
?>

<a class="regText" href="<?php echo $this->url( array('controller' => 'assignment', 'action' => 'extend-duedate')) ?>">
    Extend a due date
</a> <br /> <br />

Major: <br />
<select id="extended-duedates-filter">
   <?php foreach($majors as $major) { ?>
   <option> <?php echo $major ?> </option>
   <?php } ?>
</select>

<button id="filter-btn"> Filter </button>

<div id="async-container">
   <?php echo $this->partial("user/partials/extended-duedates.phtml", array('extDuedates' => $extDuedates, 'deleteUrl' => $deleteUrl)) ?>
</div>

<script type="text/javascript">
   $(document).ready(function() {

      $("#filter-btn").live('click', function() {
         major = $("#extended-duedates-filter").val();

         $.post(base + "/user/view-extended-duedates", { 'major' : major }, function(resp) {
            $("#async-container").html(resp);
            //$("#async-container").append("<?php //echo $this->partial('user/partials/extended-duedates.phtml',
            //        array('extDuedates' => $extDuedates, 'deleteUrl' => $deleteUrl)) ?>");
                    
         });
      });

   });
</script>
